Map<String, String> department = {
  'abi': 'Alibori',
  'ata': 'Atacora',
  'ate': 'Atlantique',
  // 'brg': 'Borgou',
  // 'cln': 'Collines',
  // 'kff': 'Kouffo',
  'Dng': 'Donga',
  'Ltl': 'Littoral',
  'Mno': 'Mono',
  'ome': 'Ouémé',
  'plt': 'Plateau',
  'zou': 'Zou',
};
Map<String, Map<String, String>> common = {
  'abi': {
    'bka': 'Banikoara',
    'gou': 'Gogounou',
    'kni': 'Kandi',
    'kma': 'Karimama',
    'mvl': 'Malanville',
    'sga': 'Segbana',
  },
  'ata': {
    'bkb': 'Boukoumbe',
    'cby': 'Cobly',
    'kru': 'Kerou',
    'kad': 'Kouande',
    'mti': 'Materi',
    'nti': 'Natitingou',
    'oss': 'Ouassa-Pehunco',
    'tga': 'Tanguieta',
    'tka': 'Toukountouna',
  },
  'ate': {
    'abc': 'Abomey-Calavi',
    'ala': 'Allada',
    'kpe': 'Kpomasse',
    'odh': 'Ouidah',
    'sva': 'So-Ava',
    'tfo': 'Toffo',
    'tri': 'Tori-Bossito',
    'ze': 'Ze',
  },
  'Dng': {'Bsl': 'Bassila', 'Cpg': 'Copargo', 'Djg': 'Djougou', 'Oke': 'Ouake'},
  'Mno': {
    'Atm': 'Athieme',
    'Bpa': 'Bopa',
    'Cme': 'Come',
    'Gpp': 'Grand-popo',
    'Hyg': 'Houeyogbe',
    'Lks': 'Lokossa'
  },
  'Ltl': {'Ctn': 'Cotonou'},
  'ome': {
    'ajr': 'Adjarra',
    'ajh': 'Adjohoun',
    'agg': 'Aguégués',
    'akm': 'AkpoMissérété',
    'avk': 'Avrankoun',
    'bnu': 'Bonou',
    'dgb': 'Dangbo',
    'smk': 'Sèmè-Kpodji'
  },
  'plt': {
    'adr': 'Adja-Ouèrè',
    'ifg': 'Ifangni',
    'ktu': 'Kétou',
    'pbe': 'Pobè',
    'skt': 'Sakété',
  },
  'zou': {
    'aby': 'Abomey',
    'agh': 'Agbangnizoun',
    'bhc': 'Bohicon',
    'cve': 'Cove',
    'djj': 'Djidja',
    'onh': 'Ouinhi',
    'zkp': 'Zakpota',
    'zgd': 'Zangnanado',
    'zdy': 'Zogbodomey'
  },
};

Map<String, Map<String, String>> district = {
  // Ozias
  'bka': {
    'aba': 'Arbonga',
    'abo': 'Atabenou',
    'avn': 'Aviation',
    'btn': 'Batran',
    'bfu': 'Bofounou',
    'bhu': 'Bonhanrou',
    'bni': 'Boniki',
    'bke': 'Bonkere',
    'bon': 'Bonni',
    'bte': 'Bonte',
    'byu': 'Bonyangou',
    'brn': 'Bourin',
    'dmu': 'Demanou',
    'dru': 'Derou Garou',
    'dbr': 'Domboure',
    'gah': 'Domboure-Gah',
    'dau': 'Dondagou',
    'fno': 'Founougo-Boutera',
    'fta': 'Founougo-Gah',
    'fgi': 'Founougo-Gorobani',
    'gam': 'Gama',
    'gmu': 'Gamarou',
    'gme': 'Gamere-Zongo',
    'gba': 'Gbangbanga',
    'gsa': 'Gbassa',
    'gni': 'Gbeniki',
    'gbi': 'Glegbabi',
    'gau': 'Gnambanou',
    'gku': 'Gnambourankorou',
    'gdo': 'Gnandarou',
    'gpu': 'Gomparou',
    'gsi': 'Gomparou Goussinrou',
    'gka': 'Gomparou-Gokpadou',
    'ggu': 'Gougnirou',
    'ggh': 'Gougnirou-Gah',
    'gmi': 'Goumori-Bayedou',
    'gih': 'Goumori-Gah',
    'gbu': 'Goumori-Gbissarou',
    'gre': 'Goure-Ede',
    'gui': 'Guiguiri',
    'gbo': 'Guimbagou',
    'gnn': 'Guinningou-Gah',
    'ito': 'Iboto',
    'igu': 'Igrigou',
    'kru': 'Kakourogou',
    'kal': 'Kali',
    'kdu': 'Kanderou',
    'kta': 'Kanderou-Kotchera',
    'keg': 'Kegamorou',
    'kih': 'Kihouhou',
    'kin': 'Kingarou',
    'kok': 'Kokey-Filo',
    'ksu': 'Kokey-Sinakparou',
    'kbu': 'Kokiborou',
    'kie': 'Kokire',
    'kom': 'Kommon',
    'kon': 'Koney',
    'kor': 'Kori Guiguiri',
    'kpa': 'Kpagaguedou',
    'kgi': 'Kpako-Gbabi',
    'kpe': 'Kpeborogou',
    'kbo': 'Kpessanrou',
    'mek': 'Mekrou',
    'mon': 'Mondoukoka',
    'moh': 'Mondoukoka-Gah',
    'nie': 'Niekoubanta',
    'nim': 'Nimbere',
    'oro': 'Orou Gnonrou',
    'oun': 'Ounet-Gah',
    'osu': 'Ounet-Sekogbaourou',
    'osi': 'Ounet-Sinakparou',
    'ppe': 'Pampime',
    'pge': 'Piguire',
    'pgu': 'Pogoussourou',
    'pot': 'Poto',
    'pga': 'Poto-Gah',
    'sku': 'Sakassinnou',
    'sma': 'Samanga',
    'smo': 'Sampeto',
    'sta': 'Satouba',
    'spu': 'Simperou',
    'sph': 'Simperou-Gah',
    'ska': 'Sionkpekoka',
    'sko': 'Sirikou',
    'sgu': 'Sissianganrou',
    'swu': 'Siwougourou',
    'soh': 'Somperoukou-Gah',
    'soa': 'Somperoukou-Gbessara',
    'son': 'Somperoukou-Yorounon',
    'snu': 'Sonnou',
    'snh': 'Sonnou-Gah',
    'swi': 'Sonwari',
    'sro': 'Soroko',
    'srh': 'Soroko Gah',
    'sny': 'Soroko Yorounou',
    'sdu': 'Soudou',
    'snn': 'Sounsoun',
    'tgn': 'Tigansou',
    'the': 'Tihoure',
    'ttu': 'Tintinmou',
    'tth': 'Tintinmou-Gah',
    'tka': 'Tokey-Banta',
    'trh': 'Toura Gah',
    'tru': 'Toura-Bio N\'Worou',
    'try': 'Toura-Yokparou',
    'wgu': 'Wagou',
    'wtu': 'Weterou',
    'yku': 'Yadikparou',
    'ybu': 'Yamberou',
    'ygi': 'Yangueri',
    'yyu': 'Yinyinpogou',
    'yse': 'Yossinande',
  },
  'gou': {
    'bdu': 'Badou',
    'bsu': 'Bagou-Sinkparou',
    'byo': 'Bogou-Yagbo',
    'bge': 'Banigoure',
    'bte': 'Bantansoue',
    'bro': 'Bepororo',
    'bga': 'Binga',
    'bor': 'Boro',
    'bdo': 'Borodarou',
    'byu': 'Bouyagourou',
    'dau': 'Dagourou',
    'dsi': 'Dassari',
    'dia': 'Diadia',
    'dgn': 'Diguisson',
    'ddu': 'Dimdimnou',
    'dje': 'Djinmele',
    'dwi': 'Donwari',
    'dgu': 'Dougou',
    'dye': 'Dougoulaye',
    'fna': 'Fanan',
    'gma': 'Gamagou',
    'gdo': 'Gando-Dari',
    'gbo': 'Gandobou',
    'gro': 'Garagoro',
    'gss': 'Gasso',
    'gms': 'Gbemoussou',
    'gsa': 'Gbessa',
    'gda': 'Gnindarou',
    'ggo': 'Gogounou-Nassabara',
    'gbr': 'Goubera',
    'gnu': 'Gounarou',
    'gha': 'Goure Dantcha',
    'kal': 'Kale',
    'kli': 'Kali',
    'kgn': 'Kangnan',
    'kwu': 'Kantakpara-Wokparou',
    'kwo': 'Kantakpara-Wokperou',
    'ksu': 'Kassirou',
    'kru': 'Kerou-Bagou',
    'kin': 'Konsenin',
    'kge': 'Kpakaguere',
    'kpi': 'Kpigourou',
    'lru': 'Lafiarou',
    'nfu': 'Nafarou',
    'obu': 'Orou-Bedou',
    'oue': 'Ouere-Bani',
    'osu': 'Ouere-Sonkerou',
    'owu': 'Ouessene-Worou',
    'pik': 'Pariki',
    'pti': 'Petit-Paris',
    'sku': 'Sonkorou',
    'sbw': 'Sori-Boro Wanrou',
    'skn': 'Sori-Kpankpanou',
    'sip': 'Sori-Peulh',
    'sro': 'Sorou',
    'sgu': 'Sougou-Gourou',
    'ski': 'Sougou-Kpantrossi',
    'sko': 'Soukarou',
    'tai': 'Taiti',
    'twi': 'Tawali',
    'tpa': 'Tchoupounga',
    'war': 'Wara',
    'wah': 'Wara-Gah',
    'wao': 'Wara-Gbidogo',
    'ypu': 'Yankpannou',
  },
  'kni': {
    'atu': 'Akoitchaou',
    'ara': 'Al Barika',
    'ake': 'Alekpare',
    'aka': 'Alfakoara',
    'ayn': 'Alibori-Yankin',
    'aru': 'Angaradebou',
    'bka': 'Bakpara',
    'bgo': 'Banigourou',
    'bki': 'Banikani',
    'bbb': 'Baobab',
    'ben': 'Bensekou',
    'bik': 'Bikougou',
    'bod': 'Boderou',
    'bop': 'Boderou-Peulh',
    'dmi': 'Damadi',
    'din': 'Dinin',
    'dip': 'Dinin Peulh',
    'dod': 'Dodondawa Somoutere',
    'ddn': 'Dodopanin',
    'dog': 'Dogban',
    'dwi': 'Donwari',
    'dwp': 'Donwari- Peulh',
    'faf': 'Fafa',
    'fir': 'Firi',
    'fou': 'Fouet',
    'fre': 'Foure',
    'gbn': 'Gambane',
    'gbp': 'Gambane-Peulh',
    'gno': 'Gando',
    'gnk': 'Gando-Kossikana',
    'gng': 'Gando-Gbiga',
    'gny': 'Gando-Yirousse',
    'gdu': 'Gbindarou',
    'gko': 'Gbokoukou',
    'gge': 'Gogbede',
    'goe': 'Gogore',
    'gop': 'Gourou Peulh',
    'hby': 'Heboumey',
    'kgd': 'Kabagbede',
    'kad': 'Kadjere',
    'kaf': 'Kandi-Fo',
    'kfp': 'Kandi-Fo-Peulh',
    'kak': 'Kassakou',
    'khe': 'Keferi-Hinkante',
    'kse': 'Keferi*-Sinte',
    'ksu': 'Kossarou',
    'ktk': 'Koutakroukou',
    'kpl': 'Kpalolo',
    'kpu': 'Kpessarou',
    'lfr': 'Lafiarou',
    'lol': 'Lolo',
    'mda': 'Madina',
    'mgo': 'Mongo',
    'mgp': 'Mongo-Peulh',
    'pad': 'Pade',
    'pap': 'Pade-Peulh',
    'ped': 'Pede',
    'pgi': 'Pedigui',
    'peg': 'Pegon',
    'pod': 'Podo',
    'saa': 'Saah',
    'ska': 'Sakatoussa',
    'sam': 'Sam',
    'sag': 'Sam-Gokirou',
    'sap': 'Sam-Peulh',
    'sek': 'Sekale',
    'sid': 'Siderou',
    'swn': 'Sinawongourou',
    'swp': 'Sinawongourou-Peulh',
    'sin': 'Sinikoussou-Beri',
    'son': 'Sondo',
    'sso': 'Sonsoro',
    'ssp': 'Sonsoro-Peulh',
    'sdu': 'Sonndou',
    'tku': 'Tankougou',
    'tkd': 'Tankougou-Dagourou',
    'tka': 'Tchoka',
    'ter': 'Teri',
    'thu': 'Thuy',
    'thy': 'Thya',
    'tis': 'Tissarou',
    'tip': 'Tissarou-Peulh',
    'tou': 'Touko',
    'won': 'Wonga',
    'zer': 'Zerman Koure',
  },
  'kma': {
    'bka': 'Bako-Maka',
    'bni': 'Banikani',
    'bzu': 'Banizoumbou',
    'blt': 'Bello-Tounga',
    'bla': 'Barni Lafia',
    'bgo': 'Bogo-Bogo',
    'bgi': 'Bongnami',
    'dgi': 'Dangazori',
    'fda': 'Fadama',
    'fka': 'Fakara',
    'fdu': 'Fandou',
    'gka': 'Garbey-Koara',
    'gko': 'Goroukambou',
    'gta': 'Goumbitchigoura',
    'gri': 'Gourou Beri',
    'kap': 'Kangara-Peulh',
    'kgi': 'Karigui',
    'Kbb': 'Karimama-Batouma-Beri',
    'kdk': 'Karimama-Dendi-Koure',
    'kta': 'Kene-Tounka',
    'kji': 'Koaratedji',
    'kfo': 'Kofounou',
    'koa': 'Kompa',
    'kti': 'Kompanti',
    'lbu': 'Loumbou-Loumbou',
    'mye': 'Machayan-Marche',
    'mya': 'Mamassy-Gourma',
    'myp': 'Mamassy-Peulh',
    'msa': 'Missira',
    'msy': 'Monsey',
    'pta': 'Petchinga',
    'sba': 'Saboula',
    'tda': 'Tondikoaria',
    'tdn': 'Tondoobon',
    'trh': 'Torioh',
    'tua': 'Toura'
  },
  'mvl': {
    'bgu': 'Bangou',
    'bla': 'Baniloua',
    'bfk': 'Banite-Fere Kire',
    'btk': 'Banite-Kouberi',
    'bcl': 'Bodjecali',
    'bch': 'Bodjecali-Chateau',
    'bfo': 'Boiffo',
    'deg': 'Degue-Degue',
    'dji': 'Djindegabi-Tounga',
    'fia': 'Fiafounfoun',
    'gaa': 'Gaabo',
    'gal': 'Galiel',
    'ger': 'Garou-Beri',
    'gti': 'Garou-Tedji',
    'gtg': 'Garou-Tedji-Gorobani',
    'gwk': 'Garou-Wenou-Kannin',
    'gdj': 'Godjekoara',
    'gan': 'Golobanda',
    'gud': 'Gorou-Djinde',
    'gss': 'Goroussoundougou',
    'gun': 'Goun-Goun',
    'ggo': 'Guene-Guidigo',
    'gze': 'Guene-Zerme',
    'iua': 'Illoua',
    'iss': 'Issene',
    'ktg': 'Kambouwo-Tounga',
    'kan': 'Kantoro',
    'kas': 'Kassa',
    'kat': 'Koara-Tedji',
    'kto': 'Kotchi',
    'klu': 'Koualerou',
    'ktj': 'Kouara-Tedji',
    'lky': 'Lakali-Kaney',
    'mdi': 'Madecali',
    'mdz': 'Madeli-Zongo',
    'mka': 'Melayakouara',
    'mll': 'Mokolle',
    'mol': 'Molla',
    'mks': 'Monkassa',
    'swt': 'Sakawan-Tedji',
    'swz': 'Sakawan-Zenon',
    'sth': 'Santche',
    'sen': 'Sende',
    'sgu': 'Sounbey-Gorou',
    'tde': 'Tassi-Djinde',
    'tti': 'Tassi-Tedji',
    'ttb': 'Tassi-Tedji-Banizounbou',
    'tta': 'Tassi-Tedji-Boulanga',
    'tsz': 'Tassi-Zenon',
    'tba': 'Tondi-Banda',
    'tzu': 'Toro-Zougou',
    'tbt': 'Toumboutou',
    'tgt': 'Tounga-Tedji',
    'wda': 'Wanda',
    'wzk': 'Wanzam-Koara',
    'wol': 'Wollo',
    'woc': 'Wolo-Chateau',
    'wyo': 'Wouro-Yesso',
  },
  'sga': {
    'btz': 'Batazi',
    'bfu': 'Bedafou',
    'bba': 'Bobena',
    'bmu': 'Boumoussou',
    'dpu': 'Diapeou',
    'fdo': 'Fondo',
    'gla': 'Gandoloukassa',
    'gaa': 'Gbarana',
    'gse': 'Gbasse',
    'gkk': 'Gbekakarou',
    'gka': 'Gbessaka',
    'gre': 'Gbessare',
    'gge': 'Goungbe',
    'gki': 'Guene Kouzi',
    'glg': 'Guenelaga',
    'kmn': 'Kamanan',
    'kba': 'Kambara',
    'kor': 'Korowi',
    'kte': 'Koute',
    'kss': 'Kpassana',
    'lte': 'Lete',
    'lbe': 'Libante',
    'lbu': 'Liboussou',
    'lfi': 'Limafrani',
    'lgu': 'Lougou',
    'mwe': 'Mafouta-Waassare',
    'mru': 'Morou',
    'nba': 'Niambara',
    'pai': 'Piami',
    'poe': 'Poela',
    'sta': 'Samtimbara',
    'szi': 'Saonzi',
    'sbi': 'Serebani',
    'ske': 'Serekibe',
    'siw': 'Sinwan',
    'sti': 'Sokotindji',
    'tkm': 'Tchakama',
    'tgi': 'Tounga-Issa',
    'waz': 'Waranzi',
    'zzi': 'Zonzi',
  },
  'bkb': {
    'agt': 'Agonte',
    'dde': 'Didompe',
    'dhn': 'Dikon Hein',
    'dkn': 'Dikouani',
    'dkm': 'Dikoumini',
    'dkt': 'Dikouteni',
    'dms': 'Dimansouri',
    'dmi': 'Dimatadonie',
    'dto': 'Dimateco',
    'dti': 'Dimatima',
    'dtk': 'Dipintakouani',
    'dpk': 'Dipokor',
    'dpt': 'Dipokor-Tchaaba',
    'dpf': 'Dipokorfontri',
    'dpl': 'Dipoli',
    'dsl': 'Dissapoli',
    'dit': 'Ditchendia',
    'iko': 'Ikounga',
    'ktc': 'Katchagniga',
    'key': 'Keyordake',
    'kot': 'Kototougou',
    'kbg': 'Koubegou',
    'kbt': 'Koubentiegou',
    'kcg': 'Koucogou',
    'kng': 'Koucongou',
    'kdd': 'Koudadagou',
    'kdh': 'Koudahongou',
    'kdg': 'Koudogou',
    'kdu': 'Kougnangou',
    'khg': 'Kouhemgou',
    'kou': 'Koukoua',
    'kkk': 'Koukouakamangou',
    'kkg': 'Koukouangou',
    'kbm': 'Koukouangou-Boukoumbe',
    'kko': 'Koukouankpangou',
    'kth': 'Koukouatchiengou',
    'kkt': 'Koukouatougou',
    'kkh': 'Koukpetihagou',
    'kpt': 'Koukpintiegou',
    'kaa': 'Koumaagou',
    'kmt': 'Koumatie',
    'kch': 'Koumontchigou',
    'knd': 'Kounadogou',
    'kna': 'Kounagnigou',
    'kak': 'Kounakogou',
    'ktt': 'Kounatchatiegou',
    'kht': 'Kountchougou',
    'kpg': 'Koupagou',
    'kpk': 'Koupagou-Korontiere',
    'oup': 'Kouporgou',
    'oss': 'Koussakou',
    'aya': 'Koussayagou',
    'eti': 'Koussetiegou',
    'coi': 'Koussocoingou',
    'cio': 'Koussoucoingou',
    'non': 'Koussounongou',
    'tag': 'Koutagou',
    'tan': 'Koutangou',
    'tat': 'Koutatiegou',
    'yag': 'Koutayagou',
    'kkm': 'Koutcha-Koumagou',
    'kha': 'Koutchantie',
    'kca': 'Koutchata',
    'kho': 'Koutchatahongou',
    'kte': 'Koutchatie',
    'ktn': 'Koutoutongou',
    'kwk': 'Kouwatakouangou',
    'kwt': 'Kouwonatougou',
    'kwr': 'Kouwotchirgou',
    'uya': 'Kouya',
    'krp': 'Kperinkpe',
    'mth': 'Mantchari',
    'ntt': 'Natchente',
    'nti': 'Natieni',
    'oko': 'Okouaro',
    'ota': 'Otanongou',
    'ouk': 'Oukounserihoun',
    'tba': 'Tabota',
    'twt': 'Tadowonta',
    'ttn': 'Takotchienta',
    'tkt': 'Takotieta',
    'tkp': 'Takpanta',
    'tso': 'Tassayota',
    'tda': 'Tatchadieta',
    'tou': 'Tatouta',
    'tpa': 'Tchapeta',
    'tki': 'Takotieta',
    'tpt': 'Takpanta',
    'tas': 'Tassayota',
    'tac': 'Tatchadieta',
    'tto': 'Tatouta',
    'tpe': 'Tchapeta',
    'tip': 'Tipaoti',
    'yat': 'Yatie',
    'zon': 'Zongo',
  },
  'cby': {
    'bag': 'Bagapodi',
    'cbl': 'Cobly',
    'dti': 'Datori',
    'gag': 'Gnangou',
    'kad': 'Kadieni',
    'kan': 'Kanadeke',
    'kol': 'Kolgou',
    'kok': 'Koukontouga',
    'knt': 'Kountori',
    'ktn': 'Kpetienou',
    'kso': 'Kpetissohoun',
    'mat': 'Matale',
    'nag': 'Nagnande',
    'nam': 'Namatienou',
    'nmo': 'Namoutchaga',
    'nan': 'Nanagade',
    'nug': 'Nouangou',
    'oru': 'Oroukouare',
    'ouk': 'Oukodoo',
    'out': 'Oukpetouhoun',
    'ouh': 'Oukpintihoun',
    'ouo': 'Ouorou',
    'oun': 'Outanonhoun',
    'ouy': 'Ouyerihoun',
    'pen': 'Pentinga',
    'ser': 'Serhoungue',
    'sie': 'Sienou',
    'sin': 'Sinni',
    'tpo': 'Tapoga',
    'tar': 'Tarpingou',
    'tha': 'Tchamonga',
    'tho': 'Tchokita',
    'tok': 'Tokibi',
    'tga': 'Touga',
    'yim': 'Yimpissiri',
    'zan': 'Zanniouri',
  },
  'kru': {
    'bbu': 'Bagoubagou',
    'bku': 'Bakoussarou',
    'bma': 'Bambaba',
    'bas': 'Bassini',
    'bat': 'Batenin',
    'ber': 'Berekossou',
    'bip': 'Bipotoko',
    'bou': 'Boukoubourou',
    'bri': 'Brignamaro',
    'djo': 'Djoleni',
    'fet': 'Fetekou',
    'fea': 'Fetekou-Alaga',
    'gam': 'Gambore',
    'gan': 'Gando Baka',
    'gat': 'Gantodo',
    'gna': 'Gnampoli',
    'gng': 'Gnangnanou',
    'gor': 'Gorobani',
    'ggn': 'Gougninnou',
    'kgr': 'Kabongourou',
    'kao': 'Kaobagou',
    'kar': 'Karigourou',
    'ked': 'Kedarou',
    'kwi': 'Kerou Wirou',
    'kkk': 'Kokokou',
    'kgu': 'Kongourou',
    'kos': 'Kossou',
    'koo': 'Kossou-Ouinra',
    'kpg': 'Kparategui',
    'mnu': 'Manou',
    'ooe': 'Ouore',
    'pik': 'Pikire',
    'pia': 'Pikire-Adaga',
    'sig': 'Sinagourou',
    'sok': 'Sokoungourou',
    'tkn': 'Tchoukagnin',
    'tbu': 'Toudakou Banyirou',
    'wnu': 'Warou N\'Gourou',
    'ymo': 'Yakin-Motoko',
    'yak': 'Yakrigorou',
    'yin': 'Yinsiga',
    'yir': 'Yiroubara',
  },
  'kad': {
    'blo': 'Bassilou',
    'bbe': 'Becket-Bourame',
    'btp': 'Becket-Peulh',
    'bim': 'Birni Maro',
    'bka': 'Birni-Kankoulka',
    'bku': 'Birni-Kpebirou',
    'bre': 'Bore',
    'bro': 'Boro',
    'bkp': 'Boroukou-Peulh',
    'byd': 'Boroyinde',
    'cca': 'Chabi Couma',
    'dmi': 'Damouti',
    'dri': 'Danri',
    'dwu': 'Darou-Wirou',
    'dku': 'Dekerou',
    'foo': 'Foo',
    'foa': 'Foo-Mama',
    'gku': 'Ganikperou',
    'gtc': 'Gantieco',
    'grp': 'Gora-Peulh',
    'ggb': 'Gorgoba',
    'gfu': 'Goufanrou',
    'gtr': 'Goutere',
    'gbk': 'Guilmaro-Bounkossorou',
    'ggs': 'Guilmaro-Garkousson',
    'gsg': 'Guilmaro-Sinakpagourou',
    'hgn': 'Hongon',
    'kbe': 'Kabare',
    'kdk': 'Kedekou',
    'ktr': 'Ketere',
    'kbr': 'Kouboro',
    'kta': 'Kpakou-Tankouga',
    'kku': 'Kpankpankou',
    'ksn': 'Kpessinin',
    'ksr': 'Kpessourou',
    'kka': 'Kpikire Koka',
    'mak': 'Maka',
    'mgr': 'Makrou-Gourou',
    'mar': 'Maro',
    'mry': 'Mary',
    'nsk': 'Nassoukou',
    'nia': 'Niarissinra',
    'nig': 'Niaro-Gninon',
    'nin': 'Niarosson',
    'nkb': 'Niekene-Bansou',
    'obs': 'Orouboussoukou',
    'ogn': 'Orougbeni',
    'oro': 'Oroukayo',
    'orf': 'Ouroufina',
    'ppa': 'Papatia',
    'pel': 'Pelima',
    'ppr': 'Poupoure',
    'skb': 'Sakabou',
    'skd': 'Sakasson-Ditamari',
    'skp': 'Sakasson-Dompago',
    'skr': 'Sekogourou',
    'ska': 'Sekogourou-Baila',
    'ser': 'Seri',
    'sku': 'Sinakpaworou',
    'sbk': 'Somboko',
    'sgo': 'Sonnougoberou',
    'swa': 'Sowa',
    'tmd': 'Tamande',
    'tac': 'Tance',
    'tsi': 'Tassigourou',
    'tko': 'Tikou',
    'tkr': 'Tokoro',
    'wem': 'Weme',
    'ybi': 'Yakabissi',
    'ykn': 'Yinkene',
    'zgo': 'Zongo',
  },
  'mti': {
    'bhn': 'Bahoun',
    'bpa': 'Bampora',
    'bgi': 'Bogodori',
    'bfi': 'Borifieri',
    'bra': 'Bourporga',
    'bhp': 'Boutouhounpingou',
    'cpi': 'Coupiani',
    'dgn': 'Dabogohoun',
    'dsr': 'Dassari',
    'dog': 'Doga',
    'feh': 'Fehoun',
    'fek': 'Fekerou',
    'fir': 'Firihoun',
    'gad': 'Gouande',
    'hol': 'Holli',
    'kdh': 'Kandeguehoun',
    'kdj': 'Kandjo',
    'kks': 'Kankini-Seri',
    'knd': 'Koneandri',
    'kti': 'Kotari',
    'ktn': 'Kouantieni',
    'krh': 'Kouarhoun',
    'kfp': 'Kouforpissiga',
    'knr': 'Koundri',
    'kkl': 'Kourou-Koualou',
    'ksg': 'Koussega',
    'kdi': 'Koutonkoudiga',
    'kho': 'Kperehoun',
    'mda': 'Madoga',
    'mhk': 'Mahontika',
    'mtr': 'Materi',
    'mer': 'Merhoun',
    'mih': 'Mihihoun',
    'nch': 'N\'Tchiega',
    'nag': 'Nagassega',
    'nak': 'Nagassega-Kani',
    'nbl': 'Nambouli',
    'nll': 'Niehoun-Laloga',
    'nod': 'Nodi',
    'nou': 'Nouari',
    'ory': 'Ouriyori',
    'pin': 'Pingou',
    'por': 'Porga',
    'pou': 'Pouri',
    'pni': 'Pourniari',
    'sak': 'Sakonou',
    'sek': 'Sekanou',
    'set': 'Setchindika',
    'sin': 'Sindori-Toni',
    'sou': 'Souomou',
    'tki': 'Tambogou-Kondri',
    'tpn': 'Tampanga',
    'tpy': 'Tampinti-Yerou',
    'tpp': 'Tampoure-Pogue',
    'thn': 'Tanhoun',
    'tkr': 'Tankouari',
    'tyn': 'Tankouayokouhoun',
    'tta': 'Tantega',
    'tti': 'Tantouri',
    'tsh': 'Tassahoun',
    'ths': 'Tchanhouncossi',
    'tkg': 'Tcharikouanga',
    'tsa': 'Tchassaga',
    'teb': 'Tebiwogou',
    'tet': 'Tetonga',
    'tia': 'Tiari',
    'tig': 'Tigninga',
    'tih': 'Tihoun',
    'tin': 'Tintonsi',
    'twg': 'Tinwega',
    'tbg': 'Toubougnini',
    'tsr': 'Toussari',
    'yan': 'Yanga',
    'ysa': 'Yansaga',
    'yed': 'Yedekahoun',
    'yon': 'Yondisseri',
    'yop': 'Yopiaka',
  },
  'nti': {
    'bag': 'Bagri',
    'ngt': 'Bangretamou',
    'brc': 'Berecingou',
    'bkr': 'Bokoro',
    'bye': 'Boriyoure',
    'dsk': 'Dassakate',
    'dpb': 'Bidapoumbor',
    'dka': 'Dikouan',
    'dtw': 'Ditawan',
    'djj': 'Djindjire-Beri',
    'dkd': 'Dokonde',
    'doy': 'Doyakou',
    'fay': 'Fayoure',
    'gmm': 'Gnagnammou',
    'kpa': 'Kampouya',
    'ktb': 'Kantaborifa',
    'ktt': 'Kantchagoutamou',
    'kga': 'Kantanginka',
    'kok': 'Koka',
    'kam': 'Kota-Monnongou',
    'ktp': 'Kotopounga',
    'kab': 'Kouaba',
    'kad': 'Kouandata',
    'kdu': 'Kouatidabirgou',
    'kbi': 'Koubirgou',
    'knu': 'Koudengou',
    'kte': 'Kouetena',
    'kku': 'Koukouabirgou',
    'kdr': 'Kounadorgou',
    'kpg': 'Kounapeigou',
    'kth': 'Kounitchangou',
    'kpc': 'Koupeico',
    'ktk': 'Koussantikou',
    'kio': 'Koussigou',
    'ktn': 'Koutanongou',
    'kti': 'Koutie',
    'ktd': 'Koutie Tchatido',
    'kwn': 'Kouwa N\'Pongou',
    'kww': 'Kouwanwangou',
    'mpm': 'Moupemou',
    'mss': 'Moussansamou',
    'ost': 'Onsikoto',
    'obu': 'Ourbouga',
    'okb': 'Ourkparbou',
    'obn': 'Ouroubonna',
    'pam': 'Pam-Pam',
    'pep': 'Peporiyakou',
    'pce': 'Perma Centre',
    'pya': 'Pouya',
    'sta': 'Santa',
    'sai': 'Sinaicire',
    'stt': 'Sountchinrantikou',
    'srk': 'Souroukou',
    'tgh': 'Tagahei',
    'tkt': 'Takonta',
    'tdm': 'Tampedema',
    'tng': 'Tchantangou',
    'tri': 'Tchirimina',
    'tmt': 'Tchoumi-Tchoumi',
    'tdt': 'Tedonte',
    'tnk': 'Tonounkonte',
    'tne': 'Tepente',
    'tte': 'Tetante',
    'tgp': 'Tignanpeti',
    'tig': 'Tigninti',
    'tik': 'Tikouani',
    'tip': 'Tipeti',
    'tor': 'Toroubou',
    'wet': 'Wetipounga',
    'wim': 'Wimmou',
    'win': 'Winke',
    'yak': 'Yakpangoutingou',
    'yar': 'Yarikou',
    'yet': 'Yetapo',
    'yim': 'Yimporima',
    'yok': 'Yokossi',
  },
  'oss': {
    'ban': 'Bana',
    'bek': 'Beket',
    'beg': 'Beket-Gah',
    'bng': 'Bonigourou',
    'bou': 'Boude',
    'ber': 'Bouerou',
    'doh': 'Doh',
    'gmb': 'Gambinou',
    'gbe': 'Gbeba',
    'gne': 'Gnemasson',
    'gng': 'Gnemasson-Gando',
    'mog': 'Mare Orou Gah',
    'nas': 'Nassou',
    'nis': 'Ningoussourou',
    'oak': 'Ouassa-Kika',
    'oam': 'Ouassa-Maro',
    'pot': 'Pehonco-Tatapouranou',
    'pho': 'Pehunco 1',
    'phu': 'Pehunco 2',
    'phg': 'Pehunco-Gah',
    'syk': 'Sayakrou',
    'syg': 'Sayakrou-Gah',
    'sau': 'Sinaou',
    'srr': 'Sinaourarou',
    'srg': 'Sinaourarou-Gah',
    'soa': 'Soaodou',
    'ssu': 'Soassararou',
    'sug': 'Somparerou-Gah',
    'tob': 'Tobre',
    'ton': 'Tonri',
    'wao': 'Wakarou',
    'woo': 'Wokou',
  },
  'tga': {
    'bat': 'Batia',
    'bia': 'Biacou',
    'bgu': 'Bongou',
    'bnt': 'Bounta',
    'bgs': 'Bourgniessou',
    'cce': 'Coroncore',
    'cot': 'Cotiakou',
    'dag': 'Daguimagninni',
    'dji': 'Djidjire-Beri',
    'ddg': 'Dondongou',
    'doi': 'Douani',
    'fin': 'Finta',
    'gbi': 'Goro-Bani',
    'htk': 'Hantekou',
    'kay': 'Kayarika',
    'kog': 'Kogniga',
    'kko': 'Kotchekougon',
    'kyo': 'Kouayoti',
    'kgr': 'Kougnieri',
    'kth': 'Koutchoutchougou',
    'mam': 'Mamoussa',
    'man': 'Manougou',
    'mat': 'Matanrgui',
    'nda': 'N\'Dahonta',
    'naf': 'Nafayoti',
    'nan': 'Nanebou',
    'nat': 'Natagata',
    'nig': 'Nigneri',
    'non': 'Nontingou',
    'now': 'Nowerere',
    'oua': 'Ouankou',
    'par': 'Parabou',
    'pem': 'Pemombou',
    'pen': 'Penitingou',
    'por': 'Porhoum',
    'pka': 'Porka',
    'smm': 'Sammongou',
    'sgu': 'Sangou',
    'spg': 'Sepounga',
    'sta': 'Sonta',
    'tah': 'Tahinkou',
    'tho': 'Tahongou',
    'tai': 'Taiacou',
    'tan': 'Tanfere',
    'tno': 'Tanongou',
    'tpk': 'Tapekou',
    'tha': 'Tchaeta',
    'thf': 'Tchatingou',
    'twk': 'Tchawassaka',
    'thb': 'Tchoutchoubou',
    'tie': 'Tiele',
    'toa': 'Tora',
    'tcc': 'Toriconcone',
    'yan': 'Yangou',
    'yar': 'Yarka',
    'yeh': 'Yehongou',
    'yey': 'Yeyedi',
    'yku': 'Youakou',
  },
  'tka': {
    'bai': 'Batitamou',
    'bbi': 'Boribansifa',
    'byn': 'Bouyagnindi',
    'dtu': 'Datakou',
    'dkk': 'Dikokore',
    'fat': 'Fatiya',
    'kou': 'Kokokou',
    'kkt': 'Kokota',
    'kar': 'Kouarfa',
    'kub': 'Kouba',
    'ktu': 'Kpentikou',
    'mak': 'Mako',
    'mou': 'Mounoumborifa',
    'mit': 'Moussitingou',
    'nab': 'Nabaga',
    'per': 'Peperkou',
    'tsr': 'Takissari',
    'tpt': 'Tampatou',
    'tpr': 'Pampegre',
    'tpb': 'Pampobre',
    'tdf': 'Tandafa',
    'tka': 'Tankokona',
    'ttg': 'Tantougou',
    'tkl': 'Tchakalakou',
    'tch': 'Tchanhorta',
    'tck': 'Tchoundekou',
    'tec': 'Tectibayaou',
    'tnt': 'Toukountouna',
    'wab': 'Wabou',
    'wsk': 'Wansokou',
  },
  'abc': {
    'abi': 'Abikouholi',
    'adj': 'Adjagbo',
    'ada': 'Adjagbo-Aidjedo',
    'add': 'Adjaglo-Aidjedo',
    'adm': 'Adjame',
    'Ado': 'Adjogansa',
    'adi': 'Adovie',
    'aga': 'Agamandin',
    'aag': 'Agassa-Godomey',
    'acs': 'Agbo-Codji-Sedegbe',
    'ago': 'Agongbe',
    'agk': 'Agonkanmey',
    'ake': 'Agonkessa',
    'agm': 'Agonme',
    'agj': 'Agonsoundja',
    'agi': 'Agori',
    'ahg': 'Ahossougbeta',
    'aha': 'Ahouato',
    'aif': 'Aifa',
    'aim': 'Aimevo',
    'ait': 'Aitchedji',
    'akc': 'Akassato Centre',
    'ako': 'Akossavie',
    'ala': 'Alansankome',
    'ale': 'Aledjo',
    'alg': 'Alegleta',
    'all': 'Alladacome',
    'amn': 'Amanhoun',
    'ana': 'Anagbo',
    'ars': 'Assrossa',
    'atc': 'Atrokpo-Codji',
    'ava': 'Avagbe',
    'azo': 'Azonsa',
    'bzo': 'Bozoun',
    'clv': 'Cite La Victoire',
    'clp': 'Cite Les Palmiers',
    'ccd': 'Cococodji',
    'cct': 'Cocotomey',
    'dbj': 'Dangbodji',
    'dsk': 'Dassekomey',
    'dge': 'Dekoungbe-Eglise',
    'dgu': 'Dekoungbe-Usine',
    'dnu': 'Denou',
    'dst': 'Dessato',
    'dkt': 'Djekpota',
    'dig': 'Djigbo',
    'dsp': 'Djissoukpa',
    'dko': 'Djoukpa-Togoudo',
    'dkm': 'Dokomey',
    'dyg': 'Domey-Gbo',
    'dsn': 'Dossounou',
    'dra': 'Drabo',
    'fan': 'Fandji',
    'fif': 'Fifonsi',
    'fig': 'Fignonhou',
    'fin': 'Finafa',
    'ggz': 'Ganganzounme',
    'gto': 'Gbegnigan-Midokpo',
    'gbb': 'Gbetagbo',
    'gbo': 'Gbodje',
    'gbw': 'Gbodje-Womey',
    'gjo': 'Gbodjo',
    'gjk': 'Gbodjoko',
    'glo': 'Glo-Tokpa',
    'gni': 'Gninkindji',
    'gon': 'Godomey-N\'Gbeho',
    'got': 'Godomey-Togoudo',
    'gol': 'Golo-Gjigbe',
    'gof': 'Golo-Fanto',
    'had': 'Hadjanaho',
    'hed': 'Hedome',
    'hel': 'Helouto',
    'hev': 'Hevie Centre',
    'hou': 'Houakomey',
    'heg': 'Houegoudo',
    'hok': 'Houeke-Gbo',
    'hoh': 'Houeke-Honou',
    'het': 'Houeto',
    'him': 'Houinme',
    'haa': 'Hounsa-Agbodokpa',
    'hyv': 'Hounyeva',
    'hze': 'Hounzevie',
    'ksk': 'Kansounkpa',
    'kol': 'Koletin',
    'kpa': 'Kpanroun',
    'kpd': 'Kpanroun-Dodomey',
    'kpv': 'Kpaviedja',
    'kpe': 'Kpe',
    'klm': 'Kpodji-Les-Monts',
    'ksa': 'Kpossidja',
    'kpo': 'Kpotomey',
    'lpx': 'La Paix',
    'lob': 'Lobozounkpa',
    'loh': 'Lohoussa',
    'mag': 'Maria-Gleta',
    'mes': 'Missebo-Espace Saint',
    'mso': 'Missessinto',
    'nin': 'Ningboto',
    'non': 'Nonhouenou',
    'ooc': 'Ouedo Centre',
    'oaa': 'Ouega-Ague',
    'oat': 'Ouega-Tokpa',
    'oun': 'Ounvenoumede',
    'pla': 'Plateau',
    'sal': 'Salamey',
    'sed': 'Sedjannanko',
    'sey': 'Sedomey',
    'slf': 'Seloli-Fandji',
    'sem': 'Seme',
    'sod': 'Sodo',
    'sog': 'Sogan',
    'sok': 'Sokan',
    'som': 'Some',
    'tak': 'Tankpe',
    'tng': 'Tchinangbegbo',
    'tmg': 'Togba Maria-Gleta',
    'tgd': 'Togbin-Daho',
    'tgk': 'Togbin-Kpevi',
    'tgf': 'Togbin-fandji',
    'tok': 'Tokan',
    'tka': 'TokanAidegnon',
    'tkp': 'Tokpa',
    'tkz': 'Tokpa-Zoungo',
    'tzn': 'Tokpa-Zoungo Nord',
    'tzs': 'Tokpa-Zoungo Sud',
    'waw': 'Wawata',
    'wta': 'Wawata-Todja',
    'wom': 'Womey Centre',
    'yea': 'Yekon-Aga',
    'yed': 'Yekon-Do',
    'yen': 'Yenandjro',
    'yev': 'Yevie',
    'yno': 'Yevie-Nougo',
    'yol': 'Yolomahouto',
    'zek': 'Zekanmey',
    'zkd': 'Zekanmey-Dome',
    'zin': 'Zinvie-Agoledji',
    'zif': 'Zinvie-Fandji',
    'ziz': 'Zinvie-Zounme',
    'zog': 'Zogbadje',
    'zop': 'Zopah',
    'zhp': 'Zopah Palmeraie',
    'zja': 'Zoundja',
    'zga': 'Zounga',
    'zoo': 'Zoungo'
  },
  'ala': {
    'acl': 'Acclohoue',
    'adi': 'Adimale',
    'adj': 'Adjadangan',
    'aja': 'Adjadji-Atinkousa',
    'ajb': 'Adjadji-Bata',
    'ajc': 'Adjadji-Cossoe',
    'ajz': 'Ajadji-Zoungbomey',
    'ado': 'Adjohoun',
    'adk': 'Adjrakandji',
    'ago': 'Agbandonou',
    'agu': 'Agbanou',
    'agk': 'Agbantokpa',
    'apk': 'Agondokpoe',
    'agy': 'Agongblamey',
    'ahi': 'Ahito',
    'aho': 'Ahota',
    'ali': 'Aligoudo',
    'all': 'Allomey',
    'aot': 'Aota',
    'ass': 'Assihoui',
    'att': 'Attogon Centre',
    'ato': 'Attotinga',
    'ath': 'Attouhonou',
    'ava': 'Avakpa',
    'aky': 'Avankamey',
    'azk': 'Avazounkpa',
    'aya': 'Ayakpata',
    'aye': 'Ayame',
    'age': 'Azohoue-Gbedjicome',
    'azh': 'Azohoue-Hongbo',
    'baw': 'Bawekanmey',
    'bol': 'Boli',
    'daa': 'Dagleta',
    'dah': 'Dahsramey',
    'djo': 'Djohoungbonou',
    'dod': 'Dodji-Aliho',
    'don': 'Dodjidangban',
    'ddm': 'Dodomey',
    'dog': 'Dogoudo',
    'doc': 'Dogoudo Ceg',
    'dou': 'Donou',
    'dov': 'Dovenou',
    'doo': 'Dovo',
    'gdh': 'Gandaho',
    'gbi': 'Gbedji',
    'ggy': 'Gbegamey',
    'goa': 'Gbeova',
    'gta': 'Gbeta',
    'gto': 'Gbeto',
    'gwe': 'Gbewele',
    'glo': 'Glotomey',
    'gou': 'Gounoutomey',
    'gos': 'Goussikpota',
    'gov': 'Govie',
    'han': 'Hanafin',
    'hgn': 'Hangnan',
    'hja': 'Hedjannansoun',
    'hes': 'Hessa',
    'het': 'Hetin',
    'hol': 'Hollansatin',
    'hou': 'Houegoudo',
    'hbt': 'Houinbatin',
    'hkk': 'Houkpokpoue',
    'hdd': 'Houndadja',
    'hgo': 'Houngbado',
    'hka': 'Hounkpa',
    'koi': 'Kotovi',
    'kpo': 'Kpodjava',
    'kdi': 'Kpodji',
    'kgy': 'Kpoguetomey',
    'lan': 'Lanmandji',
    'lis': 'Lissegazoun',
    'lok': 'Lokokpa',
    'lod': 'Loto-Denou',
    'mig': 'Migbehoue',
    'nia': 'Niaouli',
    'nou': 'Nouzounkpa',
    'seb': 'Sebo',
    'seh': 'Sehe',
    'sha': 'Sehounsa',
    'sek': 'Sekou',
    'soh': 'Sohoun',
    'sok': 'Sokoudenou',
    'sol': 'Solokoue',
    'soy': 'Soyo',
    'tan': 'Tanga',
    'tat': 'Tanga-Todo',
    'tam': 'Tanmey',
    'teg': 'Tegbo',
    'tog': 'Togazoun',
    'too': 'Togo',
    'tok': 'Tokpa',
    'toa': 'Tokpa-Avagoudo',
    'tka': 'Tokpota',
    'veh': 'Vehoui',
    'wad': 'Wadon',
    'wed': 'Wedjame',
    'wib': 'Wibatin',
    'win': 'Winyikpa',
    'wog': 'Wogo',
    'yaa': 'Yaahoue',
    'zeb': 'Zebou',
    'zin': 'Zindagba',
    'zou': 'Zoungbodji',
    'zgy': 'Zoungbomey',
    'zgd': 'Zoungoudo',
    'zli': 'Zounledji',
    'zna': 'Zounme-Aga',
    'znt': 'Zounta',
  },
  'kpe': {
    'ago': 'Adjaglo',
    'adm': 'Adjame',
    'atk': 'Adjatokpa',
    'agc': 'Aganmalome-Centre',
    'agm': 'Agbanto-Maga',
    'ags': 'Agbanto-Sotoncodji',
    'agz': 'Agbanto-Zounmin',
    'agt': 'Agoukanme Centre',
    'agd': 'Agouvodji-Daho',
    'agk': 'Agouvodji-Kpevi',
    'aha': 'Ahouango Agbidicome',
    'ahh': 'Ahouango Hinsocome',
    'aid': 'Aidjedo',
    'amo': 'Amoukonon',
    'asd': 'Assogbenou-Daho',
    'ask': 'Assogbenou-Kpevi',
    'atc': 'Atchakanme',
    'azi': 'Azizonkanme',
    'coc': 'Cocoundji',
    'cou': 'Couffonou',
    'dan': 'Danzounme',
    'ded': 'Dedome Aclome',
    'dek': 'Dedome Kpodji',
    'dog': 'Doga',
    'fif': 'Fifadji',
    'fon': 'Foncome',
    'ggh': 'Ganganhouli',
    'gwa': 'Gbedjewin Adjibamey',
    'gfi': 'Gbefadji',
    'gfa': 'Gbefadji-Aidjego',
    'gtz': 'Gbetozo',
    'gbh': 'Gboho',
    'ggn': 'Glegbotonou',
    'gnn': 'Godonoutin',
    'ggk': 'Gogotinkponme',
    'gom': 'Gome',
    'gue': 'Guezohoue',
    'hes': 'Hessa',
    'hin': 'Hinmadou',
    'hiz': 'Hinzoume',
    'hdo': 'Houedjro',
    'hgn': 'Houegan',
    'het': 'Houeton',
    'hey': 'Houeyogbe',
    'hga': 'Houngbogba',
    'kgi': 'Kougbedji',
    'kzm': 'Kouzoume',
    'kpo': 'Kpago',
    'kpi': 'Kpindjakanme',
    'kpa': 'Kpodji Atingo',
    'kpc': 'Kpodji Clotome',
    'kpt': 'Kpota',
    'lok': 'Lokogbo Gnonwa',
    'loz': 'Lokogbo Zounta',
    'lka': 'Lokassa',
    'mis': 'Missite',
    'naz': 'Nazoume',
    'non': 'Nonvignon',
    'nou': 'Nougboyifi',
    'oun': 'Ountoun',
    'ous': 'Oussa',
    'seb': 'Sebo',
    'sec': 'Secome',
    'sea': 'Segbeya Akpoutouhoue',
    'sga': 'Segbeya Amonle',
    'sgz': 'Segleya Zoundome',
    'seg': 'Segbohoue Assito',
    'sgc': 'Segbohoue Centre',
    'tea': 'Telokoe-Ahouya',
    'tod': 'Tokpa-Daho',
    'vov': 'Vovio',
    'xwl': 'Xxlacome',
    'yem': 'Yeme',
  },
  'odh': {
    'aba': 'Abatta',
    'aca': 'Acadjame',
    'adm': 'Adjohoundja-Monso',
    'ada': 'Adjra-Adovie',
    'adh': 'Adjra-Hounve',
    'adk': 'Adounko',
    'aka': 'Adounko-Ayignon',
    'agt': 'Agbadjihonto',
    'age': 'Aganlindjehoue',
    'agn': 'Agbanou',
    'agk': 'Agbanzin-Kpota',
    'akz': 'Agbanzin-Kpota Zounvlame',
    'agd': 'Agbessikpe Djika',
    'agi': 'Agouin',
    'ahd': 'Ahouandji',
    'aho': 'Ahouandjigo',
    'ahi': 'Ahouicodji',
    'azo': 'Ahozon',
    'aid': 'Aido',
    'amo': 'Amoulehoue',
    'asd': 'Assogbenou-Daho',
    'avl': 'Avlekete',
    'azi': 'Azizakoue',
    'bos': 'Bossouvi',
    'dae': 'Dangbehoue',
    'dge': 'Degoue',
    'dkn': 'Dekouenou',
    'dgi': 'Djegbadji',
    'dgm': 'Djegbame',
    'djo': 'Djondji',
    'doc': 'Docomey',
    'fkm': 'Fonkounme',
    'fsm': 'Fonsrame',
    'gak': 'Gakpe',
    'gve': 'Ganve',
    'gbe': 'Gbehonou',
    'gan': 'gbena-Nord',
    'gas': 'Gbena-Sud',
    'gtn': 'Gbeto-Nord',
    'gts': 'Gbeto-Sud',
    'gzm': 'Gbezounme',
    'gom': 'Gomey',
    'heh': 'Hehounli',
    'hio': 'Hio',
    'hiv': 'Hio Vinawa',
    'hed': 'Houakpe-Daho',
    'hjd': 'Houedjedo',
    'hly': 'Houeyiho',
    'hdv': 'Houndjava',
    'hhm': 'Hounhanmede',
    'kvf': 'Kouvenanfide',
    'kpa': 'Koasse',
    'kpo': 'Kpovi',
    'lba': 'Lebou Alafia',
    'lbc': 'Lebou Campto',
    'mek': 'Meko',
    'mtk': 'Minantinkpon',
    'oke': 'Oke-Agbede',
    'oue': 'Ouesse',
    'pah': 'Pahou Centre',
    'shn': 'Savi-Houeton',
    'sel': 'Selloli-Bazounkpa',
    'sey': 'Seyigbe',
    'sog': 'Sogbadji',
    'toh': 'Tohonou',
    'tol': 'Toligbe',
    'tov': 'Tove Kpassezounto',
    'toz': 'Tove Zobeto',
    'vas': 'Vasseho',
    'wag': 'Wagniho',
    'wom': 'Womey',
    'yam': 'Yamadjako',
    'zom': 'Zomai',
    'zok': 'Zomai-Kpota',
    'zgm': 'Zongo Malecome',
    'zic': 'Zoungbodji Centre',
    'zgo': 'Zoungoudo',
  },
  'sva': {
    'agy': 'Agbongamey',
    'agk': 'Agonmekomey',
    'agd': 'Agoundankomey',
    'adz': 'Ahomey Domey-Zounmey',
    'ahf': 'Ahomey-Fonsa',
    'ahg': 'Ahomey-Gbekpa',
    'ahl': 'Ahomey-Gblon',
    'alc': 'Ahomey-Lokpo Centre',
    'aho': 'Ahomey-Ounmey',
    'ahm': 'Ahouanmongao',
    'any': 'Anaviecomey',
    'aiy': 'Aniankomey',
    'asa': 'Assedokpa',
    'avl': 'Avlezounmey',
    'bes': 'Bessetonou',
    'dak': 'Dakomey',
    'doy': 'Dakomey-Yohonoukon',
    'dkp': 'Djekpe',
    'dog': 'Dogodo',
    'dok': 'Bokodji',
    'dom': 'Domeguedji',
    'dos': 'Dossougao',
    'ege': 'Eguekomey',
    'gsy': 'Gansougbamey',
    'gvy': 'Ganviecomey',
    'ggi': 'Gbagbodji',
    'gbt': 'Gbamey-Tchewa',
    'gmo': 'Gbegbome Ouekekome',
    'ggd': 'Gbegodo',
    'gbs': 'Gbessou',
    'gtg': 'Gbetingao',
    'glo': 'Gblonto',
    'gsd': 'Gounsoedji',
    'gsg': 'Gounsoegbamey',
    'gue': 'Guedevie',
    'gug': 'Guedevie-Gbegbessa',
    'hav': 'Have',
    'hen': 'Heni',
    'hin': 'Hindagao',
    'hlo': 'Hlouazounmey',
    'hou': 'Houndomey',
    'hhe': 'Hounhoue',
    'kin': 'Kindji',
    'kta': 'Kinto Ague',
    'ktd': 'Kinto Dokpakpa',
    'kto': 'Kinto Oudjra',
    'kcy': 'Kpacomey',
    'kpf': 'Kpafe',
    'ksk': 'Kassikomey',
    'kvy': 'Kpoviecomey',
    'lok': 'Lokpodji',
    'non': 'Nonhoueto',
    'sak': 'Sakomey',
    'sin': 'Sindomey',
    'shg': 'Sinhoungbomey',
    'soc': 'So-Chanhouetodo',
    'sok': 'Sokomey',
    'som': 'Somai',
    'tci': 'Tchinancomey',
    'thy': 'Tohokomey',
    'tot': 'Totakoun',
    'vek': 'Vekky Daho',
    'ved': 'Vekky DOogbodji',
    'yok': 'Yokagao',
    'zou': 'Zoungomey',
    'zhy': 'Zounhomey',
    'zkd': 'Zounkpode',
  },
  'tfo': {
    'Abo': 'Abolou',
    'acl': 'Aclonme',
    'ada': 'Adjaho',
    'adk': 'Adjakame',
    'add': 'Adjido',
    'agg': 'Agaga',
    'aga': 'Agahounkpokon',
    'agb': 'Agbaga',
    'agm': 'Agbame',
    'agl': 'Agblome',
    'agt': 'Agbotagon',
    'agz': 'Agbozounkpa',
    'agk': 'Agladokpa',
    'agn': 'Agon',
    'ago': 'Agonme',
    'agu': 'Ague',
    'ahl': 'Ahlankpa',
    'aho': 'Ahogbeme',
    'akl': 'Aklissa',
    'Akp': 'Akpe',
    'avi': 'Avissa',
    'aya': 'Ayahonou',
    'azo': 'Azonme',
    'aza': 'Azonsa',
    'bad': 'Badovita',
    'bak': 'Bakanme',
    'bos': 'Bossouvi',
    'cas': 'Cassagbo',
    'cog': 'Cogbo-Campement',
    'dac': 'Dame Centre',
    'dag': 'Dame-Gbedji',
    'dog': 'Dogoudo',
    'dol': 'Dolouvi',
    'dom': 'Dome',
    'dow': 'Dowa',
    'fan': 'Fandji',
    'gan': 'Ganme',
    'gbe': 'Gbede-Agonsa',
    'gom': 'Gomey',
    'gue': 'Gueme',
    'hel': 'Helita',
    'hec': 'Hessavi-Come',
    'hon': 'Honli',
    'hgt': 'Houegbo Tohome',
    'hgg': 'Houegbo-Gare',
    'hge': 'Houegle',
    'hns': 'Houenoussou',
    'hod': 'Houngo-Dame',
    'hog': 'Houngo-Gove',
    'hnv': 'Hounnouvie',
    'hym': 'Hounyeme',
    'kzn': 'Kinzoun',
    'kdk': 'Koudjananko',
    'kok': 'Kpokpa',
    'kpm': 'Kpozounme',
    'lan': 'Lanhounnou',
    'maz': 'Mazounkpa',
    'nia': 'Niarin',
    'sea': 'Sedessa Aligoudo',
    'sed': 'Sedje',
    'sdi': 'Sedji',
    'som': 'Some',
    'tak': 'Takon',
    'tof': 'Toffo-Gare',
    'tog': 'Togo',
    'tgd': 'Togoudo',
    'tgn': 'Togouin',
    'vod': 'Vodje',
    'yen': 'Yenawa',
    'zao': 'Za',
    'zek': 'Zeko',
    'zim': 'Zimbenou',
    'zoh': 'Zohounkpo',
    'zod': 'Zoundji',
    'zog': 'Zoungame',
  },
  'tri': {
    'aha': 'Adjahassa',
    'aga': 'Agazoun',
    'ago': 'Agonkon',
    'agk': 'Agouako',
    'agu': 'Agueta',
    'aho': 'Ahoueme',
    'aid': 'Aidohoue',
    'aka': 'Akadjame',
    'ana': 'Anavie',
    'ava': 'Avame Centre',
    'ayi': 'Ayikinko',
    'ach': 'Azohoue Cada Houngo',
    'acn': 'Azohoue Cada Nord',
    'acs': 'Azohoue Cada Sud',
    'acc': 'Azohoue Cada Centre',
    'azo': 'Azongo',
    'bit': 'Bossito',
    'deo': 'Denou',
    'doh': 'Dohinonko',
    'dok': 'Dokanme',
    'dus': 'Dossou-Somey',
    'fhk': 'Fassinouhokon',
    'gdk': 'Gbedakonou',
    'gdw': 'Gbedewahoue',
    'gdo': 'Gbedjougo',
    'ggd': 'Gbegoudo',
    'gtg': 'Gbetaga',
    'ghe': 'Gbehoue',
    'gov': 'Gbovie',
    'hya': 'Hayakpa',
    'hed': 'Hekandji',
    'hey': 'Hetin-Yenawa',
    'hla': 'Hla',
    'hvi': 'Honvie',
    'hdg': 'Houedaga',
    'hgg': 'Houngbagba',
    'hng': 'Houngo',
    'hun': 'Hounnonco',
    'kaa': 'Ketessa Agladji',
    'kkh': 'Kokanhoue',
    'lok': 'Lokossa',
    'mag': 'Maguevie',
    'msm': 'Massetome',
    'sei': 'Seigonme',
    'sog': 'Sogbe',
    'sok': 'Soklogbo',
    'tan': 'Tandahota',
    'toc': 'Tocoli',
    'tog': 'Togoudo',
    'tcc': 'Tori-Cada Centre',
    'tgc': 'Tori-Gare Centre',
    'wan': 'Wanho',
    'zeb': 'Zebe',
    'zgm': 'Zoungbome',
    'zgd': 'Zoungoudo',
    'znm': 'Zounme',
    'zvh': 'Zounvessehou',
  },
  'ze': {
    'ajg': 'Adjago',
    'ajk': 'Adjaka',
    'ajm': 'Adjame',
    'ajn': 'Adjan',
    'aja': 'Adjan-Gla',
    'ajh': 'Adjan-Houeta',
    'ako': 'Adjrako',
    'ado': 'Adohounsa',
    'abt': 'Agbata',
    'agd': 'Agbodjedo',
    'ahs': 'Agbohounsou',
    'agg': 'Aglangbin',
    'agn': 'Agoudenou',
    'adt': 'Agondotan',
    'ago': 'Agongbo',
    'agk': 'Agonzounkpa',
    'agi': 'Agoundji',
    'agu': 'Aguiakpa',
    'aho': 'Ahouali',
    'ahz': 'Ahozonnoude',
    'aif': 'Aifa',
    'akm': 'Akadjame',
    'akd': 'Akouedjromede',
    'akp': 'Akpali',
    'aki': 'Akpali-Do',
    'akh': 'Akpalihonou',
    'apy': 'Apkomey',
    'ana': 'Anavie',
    'avl': 'Avlessa',
    'awa': 'Awassou',
    'awo': 'Awokpa',
    'aws': 'Awonsedja',
    'ayf': 'Ayahounta-Fifadji',
    'azk': 'Azonkanme',
    'bod': 'Bodji',
    'dec': 'Dawe-Centre',
    'dja': 'Djigbe-Ague',
    'djg': 'Djigbe-Gbodje',
    'dji': 'Djitin-Aga',
    'djo': 'Djoko',
    'dod': 'Dodji-Aga',
    'dok': 'Dokota',
    'dka': 'Dokota-Aga',
    'dos': 'Dome-Seko',
    'gdh': 'Gandaho',
    'ggd': 'Gbagodo',
    'gof': 'Gbeto-Fongbo',
    'gzm': 'Gbozounme',
    'gga': 'Glegbodji Agah',
    'ggo': 'Glegbodji Do',
    'gfd': 'Gonfandji',
    'gul': 'Goulo',
    'gkm': 'Guekoumede',
    'hvk': 'Havikpa',
    'hek': 'Hekanme',
    'hdz': 'Houedazounkpa',
    'het': 'Houedota',
    'hed': 'Houedota-Djoko',
    'hgk': 'Houegnonkpa',
    'hht': 'Houehounta',
    'htt': 'Houehounta-Tozounkpa',
    'hze': 'Houeze',
    'hli': 'Hounliko',
    'hsg': 'Hounsagoudo',
    'htk': 'Hountakon',
    'kdt': 'Koudjannada-Tota',
    'kdp': 'Koundokpoe',
    'ktm': 'Kpatchame',
    'man': 'Mangassa',
    'mis': 'Missebo',
    'sek': 'Sedjannko',
    'sed': 'Sedje-Denou',
    'seh': 'Sedje-Houegoudo',
    'sep': 'Sedje-Kpota',
    'sza': 'Sedje-Zounmey-Aga',
    'sis': 'Sessivali',
    'sod': 'Sodji',
    'tan': 'Tangbo-Aga',
    'tad': 'Tangbo-Do',
    'tag': 'Tangnigbadji',
    'tay': 'Tanmey',
    'tat': 'Tanta',
    'tgn': 'Togbonou',
    'tog': 'Togoudo',
    'tmh': 'Tomasseahoua',
    'wag': 'Waga',
    'wan': 'Wankon',
    'wwas': 'Wassa',
    'waw': 'Wawata-Dandji',
    'waz': 'Wawata-Zounto',
    'wed': 'Wedjame',
    'wei': 'Wedji',
    'wot': 'Wo-Togoudo',
    'yev': 'Yevi',
    'yok': 'Yokpo-Centre',
    'znd': 'Zannoudji',
    'zzn': 'Zanzoun',
    'zer': 'Ze',
    'zew': 'Ze-Wedji',
    'zgy': 'Zoungbomey',
  },

  //Steven
  'Bsl': {
    'Adm': 'Adjimon',
    'Adr': 'Adjiro',
    'Akd': 'Akaradè',
    'Ald': 'Alédjo',
    'Alk': 'Aoro-Lokpa',
    'Ang': 'Aoro-Nago',
    'Api': 'Appi',
    'Asn': 'Assion',
    'Awo': 'Awo',
    'Bad': 'Bassila Abiguédou',
    'Bal': 'Bassila Allan',
    'Bab': 'Bassila Bakabaka',
    'Byk': 'Bayakou',
    'Bak': 'Biguina Akpassa',
    'Bnh': 'Biguina Holoudè',
    'Bnt': 'Biguina Tosso',
    'Bdi': 'Bodi',
    'Btu': 'Boutou',
    'Dnb': 'Diépani-Balimboli',
    'Dgu': 'Dingou',
    'Dge': 'Doguè',
    'Fgu': 'Frigniou',
    'Ggs': 'Guiguisso',
    'Igd': 'Igadougou',
    'Igr': 'Igbèrè',
    'Igk': 'Igbomakro',
    'Kdg': 'Kadégué',
    'Kte': 'Kaouté',
    'Kkl': 'Kikélé',
    'Kwr': 'Kodowari',
    'Kwl': 'Koïwali',
    'Kkt': 'Kprèkètè',
    'Moi': 'Manigri Oké Igboélé',
    'Mgi': 'Manigri-Ikanni',
    'Mos': 'Manigri-Oké Souangbé',
    'Mln': 'Mêlan',
    'Mdg': 'Modogui',
    'Nyl': 'Nagayilé',
    'Nbd': 'Nibadara',
    'Nrk': 'Nioro- Kolina',
    'Oli': 'Ouli',
    'Ptg': 'Partago',
    'Pnl': 'Pénélan',
    'Psl': 'Pénessoulou',
    'Smg': 'Salmanga',
    'Tba': 'Taba',
    'Tct': 'Tchétou',
    'Tbr': 'Tchimbéri',
    'Ttu': 'Tèkè-Térou',
    'Wnu': 'Wannou',
    'Wlo': 'Wolo',
    'Yri': 'Yari',
  },
  'Cpg': {
    'Adn': 'Anandana',
    'Bzr': 'Babanzaouré',
    'Bms': 'Bamisso',
    'Bsr': 'Bissinra',
    'Bmo': 'Bamisso',
    'Bmb': 'Bom-Bom',
    'Bki': 'Boro-Kouri',
    'Cna': 'Cana',
    'Cpg': 'Copargo',
    'Dkr': 'Dakpera',
    'Dph': 'Dalkpalahou',
    'Dsk': 'Djéssékou',
    'Fgu': 'Foungou',
    'Gyg': 'Galora-Yabaga',
    'Gfn': 'Gnanfounoum',
    'Gsa': 'Gossina',
    'Kkg': 'Kankoulga',
    'Khr': 'Karhum-Dora',
    'Kmr': 'Karhum-Maléro',
    'kmu': 'Karhum-Yaourou',
    'Ktb': 'Katabam',
    'Kbb': 'Koubénébéné',
    'Kkb': 'Koubokouborè',
    'Kkd': 'Koukoulbendi',
    'Ktt': 'Koutchanti',
    'Lfd': 'Lèfendi',
    'Mho': 'Maho',
    'Nmr': 'Nimourou',
    'Ndm': 'N’Dam',
    'Pbg': 'Pabégou',
    'Plg': 'Palampagou',
    'Pgt': 'Pargoutè',
    'Psb': 'Passabia',
    'Psg': 'Passangré',
    'Skd': 'Satiéka-Gbamdi',
    'Sma': 'Séma',
    'Sth': 'Sètrah',
    'Sgr': 'Singré',
    'Tho': 'Taho',
    'Tni': 'Tani',
    'Tkr': 'Tchakléro',
    'Tky': 'Tchakléro-Yaoura',
    'Tgn': 'Tigninoun',
    'Wdn': 'Wadhèrou',
    'Yka': 'Yaka',
    'Yru': 'Yarou',
  },
  'Djg': {
    "Abt": "Abintaga",
    "Atg": "Afatalanga",
    "Ags": "Agorogossi",
    "Akr": "Akèkèrou",
    "Alf": "Alfa",
    "Afi": "Alfa-Issa",
    "Agr": "Angara",
    "Agd": "Angaradébou",
    "Anb": "Angba",
    "Anm": "Anoum",
    "Bku": "Bakou",
    "Bds": "Bandessar",
    "Bdt": "Bandétchohi",
    "Bpp": "Baparapé",
    "Bsh": "Barèi-Saoupèhoun",
    "Bvh": "Barèi-Vaaha",
    "Bri": "Bari",
    "Brn": "Bariénou",
    "Bsl": "Bassala",
    "Btl": "Batoulou",
    "Blf": "Belléfoungou",
    "Ber": "Béri",
    "Bbh": "Bonborh",
    "Btk": "Bortoko",
    "Bgu": "Bougou",
    "Blm": "Bouloum",
    "Bmi": "Boumvari",
    "Bgr": "Boungourou",
    "Dbg": "Dabogou",
    "Dgs": "Dangoussar",
    "Dng": "Danogou",
    "Drg": "Daringa",
    "Ddr": "Dèdèra",
    "Dmh": "Démsihou",
    "Ddg": "Déndougou",
    "Dwa": "Déwa",
    "Dkg": "Djakpingou",
    "Dgn": "Donga",
    "Dwr": "Donwari",
    "Fna": "Fana",
    "Fmz": "Formagazi",
    "Fmb": "Foumbéa",
    "Fgn": "Founga",
    "Fyo": "Foyo",
    "Gah": "Gah",
    "Ggm": "Gangamou",
    "Gga": "Gaouga",
    "Gbs": "Gbessou",
    "Gng": "Gnansonga",
    "Gnb": "Gnogambi",
    "Gnr": "Gnonri",
    "Ggg": "Gogoniga",
    "Gds": "Gondessar",
    "Grb": "Gorobani",
    "Gso": "Gosso",
    "Gbk": "Goumbakou",
    "Ism": "Issamanga",
    "Kkn": "Kakabounou",
    "Kkd": "Kakindoni",
    "Kmh": "Kamouhou",
    "Klr": "Kilir",
    "Kha": "Koha",
    "Kkk": "Kokossika",
    "Kld": "Kolocondé",
    "Kks": "Kolokondé-Saoupèhoun",
    "Krk": "Korokou",
    "Kua": "Koua",
    "Kli": "Kourli",
    "Kpl": "Kpali",
    "Kml": "Kpamalangou",
    "Kpd": "Kpandouga",
    "Kpy": "Kpaouya",
    "Kpr": "kpara",
    "Kps": "Kparsi",
    "Kth": "Kpatouhou",
    "Kyr": "Kpayèroun",
    "Kbc": "Kpébouco",
    "Kpg": "Kpégounou",
    "Lmb": "Léman-Bogou",
    "Lmd": "Léman-mandè",
    "Lra": "Lira",
    "Mdn": "Madina",
    "Mng": "Minanga",
    "Mne": "Monè",
    "Mmg": "Monmongou",
    "Mwh": "Morwatchohi",
    "Mla": "Mounla",
    "Ngh": "Nagatchohi",
    "Nlh": "Nalohou",
    "Nng": "Nanogou",
    "Nmn": "Noumanè",
    "Okl": "Onklou",
    "Phn": "Pahanoun",
    "Prg": "Paparanga",
    "Ptg": "Partago",
    "Plb": "Pélébina",
    "Ppp": "Pétoni-Poho- Partago",
    "Ppg": "Pétoni-Poho-Gorobani",
    "Ptk": "Potokou",
    "Spn": "Saoupèhoun",
    "Sph": "Sapaha",
    "Ssr": "Sassirou",
    "Shs": "Sehvessi",
    "Sla": "Sèlra",
    "Slr": "Sèlrou",
    "Sru": "Sérou",
    "Sns": "Sinassingou",
    "Sso": "Sosso",
    "Sbk": "Soubroukou",
    "Tif": "Taïfa",
    "Thu": "Tamohoun",
    "Tbu": "Tébou",
    "Tds": "Téprédjissi",
    "Twu": "Tèwaou",
    "Ttb": "Timtim-Bongo",
    "Tko": "Toko-Toko",
    "Tlr": "Tolra",
    "Vhi": "Vanhoui",
    "Wgu": "Wargou",
    "Wsa": "Wassa",
    "Wwe": "Wèwè",
    "Yrk": "Yarakèou",
    "Ysg": "Yorossonga",
    "Zgb": "Zémbougou-Béri",
    "Zgo": "Zongo",
    "Znt": "Zountori",
  },
  'Oke': {
    "Add": "Adédéwo",
    "Adj": "Adjêdè",
    "Agb": "Agbandarè",
    "Agg": "Aguéou-garba",
    "Aks": "Akoussitè",
    "Akp": "Akpadè",
    "Aly": "Alayomdè",
    "Alk": "Alitokoum",
    "Asd": "Assaradè",
    "Ass": "Assodè",
    "Atc": "Atchakitam",
    "Atk": "Atchankomou",
    "Atl": "Atchankpa-Kolah",
    "Awl": "Awanla",
    "Awb": "Awotobi",
    "Bdj": "Badjoudè",
    "Bpp": "Baparapéï",
    "Bst": "Bissétougou",
    "Bhd": "Bohomdo",
    "Dka": "Daka",
    "Gao": "Gao",
    "Gbu": "Gbaou",
    "Gnl": "Gnalo",
    "Ggb": "Gnangba Kabia",
    "Itc": "Itchèlli",
    "Icd": "Itchodè",
    "Kdl": "Kadolassi",
    "Kgn": "Kagnifêlê",
    "Kpl": "Kakpala",
    "Kkp": "Kakpéssia",
    "Kte": "Kantè",
    "Ksa": "Kassua-Allah",
    "Kwd": "Kawado",
    "kmk": "Kim-Kim",
    "Kmd": "Komdè",
    "Kth": "Komtcha",
    "Kbl": "Koubly",
    "Kkl": "Koukoulounda",
    "Kkr": "Kpakpalaré",
    "Kfa": "Kpéli-fada",
    "Klt": "Kpélité",
    "Kpd": "Kpéloudè",
    "Lda": "Landa",
    "Mdj": "Madjatom",
    "Mmi": "Mami",
    "Mkp": "Mankpassi",
    "Ndd": "N’Djakada",
    "Omr": "Ouramaré",
    "Pmu": "Pamou",
    "Sbt": "Sobitè",
    "Snh": "Sonaholou",
    "Snt": "Sonaté",
    "Tlt": "Talinta",
    "Tld": "Tchaladè",
    "Tch": "Tchalinga",
    "Tgy": "Tchingayaré",
    "Tci": "Tchitchakou",
    "Trb": "Troucaré-Bas",
    "Wkt": "Wakitè",
    "Wke": "Wèkètè",
    "Yms": "Yamsalé",
  },
  "Atm": {
    "Abl": "Abloganmè",
    "Adm": "Adamè",
    "Ads": "Adankpossi",
    "Adl": "Adanlokpé",
    "Adh": "Adhamè",
    "Adc": "Adjassinhoun – Condji",
    "Adv": "Adjovè",
    "Agb": "Agbédranfo",
    "Agd": "Agbobada",
    "Agg": "Agbogbomey",
    "Agw": "Agniwédji",
    "Agh": "Aguidahoué",
    "Ahh": "Ahoho",
    "Akn": "Akonana",
    "All": "Allounkoui",
    "Anh": "Anatohoué",
    "Ass": "Assèdji-Agonsa",
    "Asd": "Assèdji-Daho",
    "Ask": "Assékomè",
    "Atc": "Atchannou",
    "Ath": "Atchontoé",
    "Atg": "Athiémégan",
    "Adj": "Avédji",
    "Avg": "Avégodo",
    "Awk": "Awakou",
    "Awm": "Awamè-Agbovèdji",
    "Awp": "Awamè-Kponou",
    "Ayc": "Ayoucomè",
    "Azl": "Azonlihoué",
    "Bch": "Bocohoué",
    "Cdj": "Condji-Agnamè",
    "Dkp": "Dékpoé",
    "Dvd": "Dévèdodji",
    "Dvm": "Dévèmè",
    "Dng": "Don-Agbodougbé",
    "Dnk": "Don-Kondji",
    "Dnn": "Donon",
    "Gbj": "Gbédji",
    "Ghk": "Gbéhossou-Kponou",
    "Glt": "Gléta",
    "Gdn": "Goudon",
    "Hhm": "Hahamè",
    "Hkp": "Hokpamè",
    "Hgl": "Houèglé",
    "Hnp": "Hounkpon",
    "Kdj": "Kodji",
    "Kkp": "Kodji Kponou",
    "Knh": "Konouhoué",
    "Kdh": "Koundohounhoué",
    "Kpn": "Kpinnou",
    "Kpi": "Kpodji",
    "Mdi": "Madéboui",
    "Szp": "Sazouékpa",
    "Szk": "Sazué Kpota",
    "Svi": "Sèvotinou",
    "Tdc": "Tadocomè",
    "Tch": "Tchicomey",
    "Tgl": "Togblo",
    "Tgu": "Toguido",
    "Zdn": "Zindonou",
    "Zhn": "Zounhouè  Kpakpassa",
  },
  "Bpa": {
    "Adj": "Adjamè",
    "Agb": "Agbodji",
    "Agh": "Agboh",
    "Agg": "Agongoh",
    "Ags": "Agonsa",
    "Ahl": "Ahloumè",
    "Akk": "Akokponawa",
    "Akl": "Akplènou",
    "Ate": "Atoè",
    "Ath": "Atohoué",
    "Agm": "Avéganmè",
    "Bda": "Badazouin",
    "Blm": "Bolimè",
    "Ddo": "Dado",
    "Dkp": "Dakpla",
    "Dst": "Dansatingo",
    "Dev": "Dévèdji",
    "Dho": "Dhodho",
    "Dja": "Djadji",
    "Dji": "Djèkian",
    "Ddj": "Djidjozoun",
    "Djf": "Djofloun",
    "Dgu": "Doguia",
    "Fan": "Fandihouin",
    "Fon": "Foncomè",
    "Gan": "Gantitomey",
    "Gba": "Gbakpodji",
    "Gbd": "Gbèdècomè",
    "Gbc": "Gbédji-Comè",
    "Gbe": "Gbètocomè",
    "Gbo": "Gbozèhouè",
    "Gni": "Gnidonou",
    "Hgn": "Hangnanmè",
    "Heh": "Hêgoh",
    "Hin": "Hinkpèmè",
    "Hmb": "Hombêtè",
    "Hnh": "Honhoui",
    "Htk": "Hontokpomè",
    "Hga": "Houanguia",
    "Hgy": "Houéganmey",
    "Hgb": "Houègbo",
    "Hng": "Houngoh",
    "Hgm": "Hounguémè",
    "Hvn": "Hounvè",
    "Hnv": "Hounviatouin",
    "Kwh": "Kowèho",
    "Kpv": "Kpavè",
    "Kpd": "Kpindjicomè",
    "Kpi": "Kpindjigbédji",
    "Kpt": "Kplatoè",
    "Kpn": "Kpodin",
    "Kpa": "Kpota",
    "Lgl": "Logloé",
    "Lfi": "Lonfin",
    "Mss": "Massè",
    "Mds": "Médéssèdji",
    "Mdt": "Mèdétogbo",
    "Msf": "Missiafo",
    "Oua": "Ouassa-Kpodji",
    "Ouo": "Ouocomè",
    "Ous": "Oussa Tokpa",
    "Ovn": "Ovoun",
    "Ozd": "Ozouédjamè",
    "Pst": "Possotomè",
    "Shm": "Sèhomi-Datoh",
    "Smi": "Sèhomi-Kogbomè",
    "Shb": "Sèhougbato",
    "Sik": "Sinkpè-Gbolossouhoué",
    "Tve": "Tanvè",
    "Tch": "Tchanhoué-Comè",
    "Tck": "Tchantchankpo",
    "Tez": "Tèkozouin",
    "Thn": "Tohonou",
    "Tha": "Tohouéta",
    "Thk": "Tohouéta Akloh",
    "Tpk": "Tokpoé",
    "Twu": "Towénou",
    "Yeg": "Yêgodoé",
    "Yto": "Yêtoè",
    "Ziw": "Zinwégoh",
    "Ziz": "Zizaguè",
    "Zon": "Zoungbo",
    "Zgb": "Zoungbo-Mission",
  },
  'Cme': {
    "Acl": "Aclomè",
    "Agt": "Agatogbo",
    "Agb": "Agblotomé",
    "Agm": "Agoutomè",
    "Adj": "Ahouandjigo Codji",
    "Aph": "Apéhvédji",
    "Avd": "Avédji",
    "Azn": "Azannou",
    "Bwe": "Bowé-Gbédji",
    "Ccc": "Cocoucodji",
    "Dgo": "Dégouè",
    "Dex": "Deux Kilos",
    "Djc": "Djacoté",
    "Dhi": "Dohi",
    "Gdm": "Gadomé",
    "Gtv": "Gativé",
    "Gbe": "Gbèdévinou",
    "Gbo": "Gboguinhoué",
    "Ggg": "Gonguêgbo",
    "Ggp": "Gonguêkpè",
    "Gzn": "Guézin Ahouandjigo",
    "Gzi": "Guézin Donhuinou",
    "Ggd": "Guézin Gbadou",
    "Gzz": "Guézin Zinkpanou",
    "Hgd": "Hongodé",
    "Hnn": "Honnougbo",
    "Hvc": "Honvê-comè",
    "Hdv": "Hôtel de ville",
    "Kde": "Kandé",
    "Kpt": "Kpétékan",
    "Kpu": "Kpétou",
    "Kpg": "Kpétou-Gahouê",
    "Kpi": "Kpodji",
    "KPg": "Kpongonou",
    "Mdj": "Maison des jeunes",
    "Mdh": "Mèdémahoué",
    "Mzt": "Mèzintomè",
    "Mbr": "Mon Berger",
    "Mgn": "Mongnonhoui",
    "Ngo": "Nongo",
    "Pdc": "Pédacomè",
    "Siv": "Sivamé",
    "Ssi": "Sossigbé",
    "Suk": "Soukpotomé",
    "Tkn": "Tokan",
    "Tsh": "Tossouhon",
    "Thn": "Totchon-Agni",
    "Tve": "Tovè",
    "Zon": "Zounta",
  },
  'Gpp': {
    "Adk": "Adankpé",
    "Adm": "Adimado",
    "Adh": "Adjaha",
    "Adj": "Adjigo",
    "Agn": "Agonnèkanmey",
    "Age": "Agoué",
    "Agu": "Agoué Gbédjin",
    "Aks": "Akodessewa",
    "All": "Allongo",
    "Apt": "Apoutagbo",
    "Avo": "Avlo",
    "Avl": "Avlo Houta",
    "Awe": "Awamè",
    "Ayi": "Ayiguinnou",
    "Bth": "Bathoto",
    "Cnh": "Conho",
    "Ctc": "Cotocoli",
    "Dvi": "Dévikanmey",
    "Djm": "Djanglamey",
    "Ewc": "Ewé Condji",
    "Fol": "Folly Condji",
    "Gbw": "Gbèawa",
    "Gbd": "Gbédji",
    "Gbo": "Gbéhoué Ouatchi",
    "Gbe": "Gbéhoué Pédah",
    "Gnh": "Gninhountimè",
    "Gni": "Gnito",
    "Gon": "Gountoeto",
    "Hku": "Hakouè",
    "Hml": "Hanmlangni",
    "hev": "Hêvê",
    "Hei": "Heyi Gbadji",
    "Hcj": "Hilla Condji",
    "Hdj": "Houndjohoundji",
    "Hkn": "Hounkounnou",
    "Hnk": "Hounsoukoè",
    "Kut": "Kouèta",
    "Kpa": "Kpablè",
    "Ktc": "Kpatcha-Condji",
    "Kpe": "Kpêko",
    "Kpo": "Kpovidji",
    "Lui": "Louis Condji",
    "Mis": "Missihoun Condji",
    "Ncu": "Nicoué Condji",
    "Onk": "Onkuihoué",
    "Sli": "Saligato",
    "Sza": "Sazué",
    "Sho": "Seho Condji",
    "Shn": "Sohon",
    "Tla": "Tala",
    "Tdj": "Todjonoukoin",
    "Tkl": "Toklanhon",
    "Tkm": "Tokpa Monoto",
    "Tka": "Tokpa-Aïzo",
    "Tlk": "Tolèbèkpa",
    "Tom": "Tomadjihoué",
    "Vod": "Vodomey",
    "Ycd": "Yodo Condji",
    "Zgb": "Zogbédji",
  },
  'Hyg': {
    "Adj": "Adjamè",
    "Ado": "Adjigo",
    "Adr": "Adromè Gbéto",
    "Adm": "Adromè Kpovidji",
    "Age": "Aglè",
    "Agn": "Agongoh",
    "Agh": "Aguêhon",
    "Ahl": "Ahouloumè",
    "Akl": "Akloh",
    "All": "Allogo",
    "Dhe": "Dahè-Aklo",
    "Dhg": "Dahè-Gbédji",
    "Dgk": "Dahè-Kpodji",
    "Dnh": "Danhoué",
    "Dnk": "Danklo",
    "Dve": "Davè",
    "Dvd": "Dévèdji",
    "Ddg": "Didongbogoh",
    "Djt": "Djètoè",
    "Dji": "Djibio",
    "Dod": "Dodji",
    "Dtu": "Doutou",
    "Dta": "Doutou – Akloh",
    "Dtf": "Doutou- Fifadji",
    "Dth": "Doutou- Hèhouin",
    "Dtk": "Doutou -Kpodji",
    "Dre": "Drè",
    "Drl": "Drè-Lonmnava",
    "Ekn": "Ekindji",
    "Ghe": "Gahoué",
    "Ghi": "Gahouin",
    "Gve": "Gavè",
    "Gdg": "Gbadagli",
    "Gbg": "Gbagbonou",
    "Gbh": "Gbahossouhoué",
    "Gbd": "Gbédji",
    "Gbo": "Gboho",
    "Gnm": "Gnamako",
    "Gnt": "Gnitonou",
    "Ggo": "Gogohondji",
    "Gfn": "Gonfiocomey-Nord",
    "Gni": "Gonfiocomey-Sud",
    "Hcn": "Hécondji",
    "Hid": "Hindè",
    "Hls": "Hlassigounmè",
    "Hla": "Hlassigounmè-Akloh",
    "Hnn": "Honnougbo",
    "Hna": "Houankpa",
    "Hkp": "Houankpato",
    "Hth": "Houétihoué",
    "Hun": "Houingah-Houégbé",
    "Hin": "Houingah-Salahoué",
    "Hva": "Hounvi Atchago",
    "Kwn": "Kowénou",
    "Kpn": "Kpansouingoh",
    "Kpk": "Kpassakanmè",
    "Ktu": "Kpétou-Gbadji",
    "Lgo": "Logohoué",
    "Lkh": "Lokohoué",
    "Mbi": "Maïboui",
    "Mab": "Maïboui -Akloh",
    "Mnk": "Manonkpon",
    "Nkn": "N’konouhoué",
    "Sbo": "Sèbo",
    "Swc": "Séwacomey",
    "Shn": "Sohounmè",
    "Tgb": "Togbonou",
    "Thn": "Tohonou",
    "Thi": "Tohouin",
    "Tka": "Tokpa",
    "Zgn": "Zoungbonou",
    "Zun": "Zounmè",
  },
  'Lks': {
    "Abl": "Ablodé",
    "Adj": "Adjakomey",
    "Adi": "Adjigo-Kpodavè",
    "Adh": "Adjohoué",
    "Ard": "Adrodji",
    "Ado": "Adrogbo",
    "Agm": "Agamè",
    "Agn": "Agnigbavèdji",
    "Agi": "Agnito",
    "Agt": "Agnito-Tchicomey",
    "Agv": "Agnivèdji",
    "Ago": "Agonkanmè",
    "Age": "Agonvè",
    "Aht": "Ahotissa",
    "Ahm": "Ahouamè",
    "Akd": "Akodédjro",
    "Ali": "Aligoudo",
    "Ati": "Atikpéta",
    "Ani": "Atinmado",
    "Azs": "Azizossa",
    "Dsi": "Dansihoué",
    "Dkm": "Dékanmè",
    "Dsa": "Dessa",
    "Dje": "Djèhadji",
    "Djo": "Djondji-Zounmè",
    "Dkn": "Doukonta",
    "Fgb": "Fongba",
    "Gdj": "Gandjazounmè",
    "Gwt": "Ganwotissa",
    "Gbd": "Gbodédji",
    "Glo": "Glo",
    "Gue": "Guéhounkon",
    "Gui": "Guinkomey",
    "Hld": "Hlodo",
    "Hun": "Houanmè",
    "Hue": "Houédaho",
    "Ksa": "Kessawè",
    "Kin": "Kinwédji",
    "Kon": "Koudo",
    "Kpl": "Kplogodomè",
    "Kpt": "Kpota",
    "Lgo": "Lègo",
    "Lgb": "Logbo",
    "Mdh": "Médéhounta",
    "Mkp": "Monkpa-Sèdji",
    "Odm": "Ouèdèmè-Cada",
    "Oud": "Ouèdèmè-Djanglanmè",
    "Sgu": "Saguè",
    "Sdj": "Sèdjè-Gléta",
    "Ssh": "Sessèhoukanmè",
    "Tkn": "Takon-Zongo",
    "Tch": "Tchicomey",
    "Tdd": "Têdéado",
    "Tnu": "Tinou",
    "Tdg": "Todoga",
    "Tgu": "Toguèmè",
    "Tkp": "Tokpa",
    "Tot": "Tota-Kindji",
    "Tti": "Totinga",
    "Tzu": "Tozounmè",
    "Tzo": "Tozounmè-Gbédji",
    "Vha": "Vêha",
    "Ynw": "Yènawa",
    "Zun": "Zoungamè",
    "Zuh": "Zounhouè",
  },
  'Ctn': {
    "Abc": "Abokicodji Centre",
    "Acl": "Abokicodji Lagune",
    "Adc": "Adjaha- Cité",
    "Adj": "Adjégounlè",
    "Ado": "Adogléta",
    "Agt": "Agbato",
    "Agb": "Agbodjèdo",
    "Ags": "Agbodjèdo Ste Rita",
    "Agl": "Agla-Agongbomey",
    "Agk": "Agla-Akplomey",
    "Afg": "Agla-Figaro",
    "Agn": "Agla-Finafa",
    "Alp": "Agla-les Pylônes",
    "Alc": "Agla-Petit Château",
    "Asg": "Agla-Sud",
    "Agi": "Agontinkon",
    "Anc": "Agounvocodji",
    "Ahg": "Ahogbohouè-Cité de l’expérience",
    "Aga": "Ahogbohouè-Cité Eucaristie",
    "Ahl": "Ahouanlèko",
    "Aha": "Ahouansori Agata",
    "Ahu": "Ahouansori Agué",
    "Ahi": "Ahouansori Ladji",
    "Ahr": "Ahouansori Towéta",
    "Aho": "Ahouansori Towéta Kpota",
    "Ahs": "Ahouassa",
    "Aib": "Aibatin Kpota",
    "Abd": "Aibatin  dodo",
    "Aid": "Aidjèdo",
    "Ada": "Aidjèdo Ahito",
    "Adg": "Aidjèdo Gbègo",
    "Aiv": "Aidjèdo Vignon",
    "Akg": "Akogbato",
    "Apa": "Akpakpa Dodomè",
    "Avl": "Avlékété Jonquet",
    "Avt": "Avotrou Aïmonlonfidé",
    "Avg": "Avotrou Gbègo",
    "Avo": "Avotrou Houézèkomè",
    "Ayl": "Ayélawadjè",
    "Aye": "Ayélawadjè Agongomè",
    "Boc": "Bocossi Tokpa",
    "Cad": "Cadjèhoun Agonga",
    "Caj": "Cadjèhoun Aupiais",
    "Caa": "Cadjèhoun Azalokogon",
    "Cdj": "Cadjèhoun Détinsa",
    "Cdh": "Cadjèhoun Gare",
    "Cdk": "Cadjèhoun Kpota",
    "Dgb": "Dagbédji-Sikê",
    "Dnj": "Dandji",
    "Ddj": "Dandji Hokanmè",
    "Dtk": "Dantokpa",
    "Dep": "Dédokpo",
    "Dje": "Djèdjè-Layé",
    "Dij": "Djidjè",
    "Dai": "Djidjè Aïchédji",
    "Dnt": "Donaten",
    "Dta": "Dota",
    "Eng": "Enagnon",
    "Enn": "Enagnon-Sikê",
    "Fdj": "Fidjrossè Centre",
    "Fdr": "Fidjrossè Kpota",
    "Ffi": "Fifadji",
    "Ffo": "Fifadji Houto",
    "Fft": "Fifatin",
    "Fgn": "Fignon-Sikê",
    "Fna": "Finagnon",
    "Fyg": "Fiyégnon Houta",
    "Fyj": "Fiyégnon Jacquot",
    "Gkp": "Gankpodo",
    "Gba": "Gbèdagba",
    "Gdg": "Gbèdégbé",
    "Gbg": "Gbèdiga  Guêdêhoungue",
    "Gbw": "Gbèdjèwin",
    "Gdr": "Gbèdjromèdé",
    "Gdm": "Gbèdjromèdé Sud",
    "Gdk": "Gbédokpo",
    "Gdd": "Gbèdomidji",
    "Gby": "Gbégamey Ahito",
    "Gyc": "Gbégamey Centre",
    "Gyd": "Gbégamey Dodo Ayidjè",
    "Gyg": "Gbégamey Gbagoudo",
    "Gyh": "Gbégamey Mifongou",
    "Gbn": "Gbènan",
    "Gno": "Gbénonkpo",
    "Gkn": "Gbénonkpo",
    "Gto": "Gbéto",
    "Gdj": "Gbodjètin",
    "Giy": "Guinkomey",
    "Hve": "Haie Vive",
    "Hid": "Hindé Nord",
    "Hsd": "Hindé Sud",
    "Hly": "Hlacomey",
    "Hzt": "Hlazounto",
    "Heh": "Houéhoun",
    "Hnu": "Houénoussou",
    "Hns": "Houénoussou Ste Rita",
    "Hyh": "Houéyiho",
    "Hyn": "Houéyiho Tanou",
    "Ird": "Irédé",
    "Jri": "Jéricho Sud",
    "Jrh": "Jéricho  Nord",
    "Kid": "Kindonou",
    "Khn": "Kouhounou",
    "Kwb": "Kowégbo",
    "Kpk": "Kpankpan",
    "Kpd": "Kpondéhou",
    "Ktm": "Kpondéhou Tchémè",
    "Lcc": "Les Cocotiers",
    "Lmn": "Lom-Nava",
    "Mdr": "Mèdédjro",
    "Mtn": "Mènontin",
    "Mid": "Midédji",
    "Mdo": "Midombo",
    "Mfg": "Mifongou",
    "Mnk": "Minonkpo Wologuèdè",
    "Mtc": "Minontchou",
    "Msb": "Missèbo",
    "Mik": "Missèkplé",
    "Mis": "Missessin",
    "Mss": "Missité",
    "Mte": "Missité",
    "Mie": "Missité-Sikê",
    "Mse": "Missogbé",
    "Nvm": "N’vènamèdé",
    "Nvp": "Nouveau Pont",
    "Ohe": "Ohe",
    "Sjg": "Saint Jean Gbèdiga",
    "Sdm": "Sèdami",
    "Som": "Sèdjro Saint Michel",
    "Sgn": "Sègbèya Nord",
    "Sgs": "Sègbèya Sud",
    "Shg": "Sèhogan-Sikê",
    "Snd": "Sènadé Sékou",
    "Sne": "Sènandé",
    "Stv": "Sètovi",
    "Sjc": "Sodjèatinmè Centre",
    "Sde": "Sodjèatinmè Est",
    "Sdo": "Sodjèatinmè Ouest",
    "Sul": "Suru Léré",
    "Tnt": "Tanto",
    "Tch": "Tchanhounkpamè",
    "Tde": "Todoté",
    "Tkh": "Tokpa Hoho",
    "Tpl": "Tokplégbé",
    "Tno": "Tonato",
    "Vdk": "Vèdoko",
    "Vdj": "Vodjè Allobatin",
    "Vda": "Vodjè Ayidoté",
    "Vdc": "Vodjè Centre",
    "Vdf": "Vodjè Finagnon",
    "Vdt": "Vodjè kpota",
    "Vsa": "Vossa",
    "Vsk": "Vossa-Kpodji",
    "Xlk": "Xwlacodji Kpodji",
    "Xwl": "Xwlacodji Plage",
    "Ygb": "Yagbé",
    "Yem": "Yémicodji",
    "Ynw": "Yénawa",
    "Ynd": "Yénawa Daho",
    "Yff": "Yénawa-Fifadji",
    "Yvd": "Yévèdo",
    "Zgb": "Zogbo",
    "Zgo": "Zogbohouè",
    "Zng": "Zongo Ehuzu",
    "Zgn": "Zongo Nima",
  },
  'ajr': {
    'adv': 'Adovié',
    'adg': 'Adovié Alaga',
    'adj': 'Adjinan',
    'adn': 'Adjinan-Aga',
    'adh': 'Adjati-Djogbèhouè',
    'adt': 'Adjati-vèdo',
    'agg': 'Agaougbéta',
    'aga': 'Agata',
    'atp': 'Agbomey-Takplikpo',
    'agt': 'Agaougbéta',
    'abt': 'Agboto',
    'agl': 'Aglogbè',
    'ayz': 'Ayihounzo',
    'alk': 'Alladako',
    'ald': 'Alladako-Dégoèto',
    'ang': 'Anagbo',
    'bkv': 'Bokovi-Tchaka',
    'djv': 'Djavi',
    'djz': 'Djavi-Zèbè',
    'djw': 'Djèvié -Wadon',
    'dhg': 'Do-Hongla',
    'dav': 'Dossouvié',
    'dgb': 'Drogbo',
    'gsk': 'Gassako',
    'ggt': 'Gbangnito',
    'ghy': 'Gbéhamey',
    'hhm': 'Hahamè',
    'hvk': 'Hêvié-Kpota',
    'hgb': 'Houêgbo',
    'hhk': 'Hounhouèko',
    'hgs': 'Hounsa-Assiogbossa',
    'hsv': 'Hounsinvié',
    'hnv': 'Hounvè',
    'hvc': 'Honvié Centre',
    'kpt': 'Kpota',
    'ldg': 'Lindja-Dangbo',
    'kdv': 'Kpadovié',
    'kvd': 'Kpovié-Gbada',
    'mlh': 'Malanhoui',
    'mkd': 'Malanhoui-Kpodo',
    'mdj': 'Médédjonou',
    'mdg': 'Mèdédjonou-Gbéhadji',
    'ouk': 'Ouèkè',
    'sdj': 'Sèdjè',
    'sm': 'Sèmè',
    'sgt': 'Sèdjè-Gbéta',
    'st': 'Sota',
    'stt': 'Sota-Tchémè',
    'tnm': 'Tanmè',
    'thk': 'Tchakou',
    'tkm': 'Tokomè',
    'vjn': 'Vidjinan',
    'yv': 'Yèvié',
  },
  'ajh': {
    'abt': 'Abato',
    'akt': 'Abéokouta',
    'abd': 'Abidomey',
    'agk': 'Agbakon',
    'agm': 'Agué-Milahin',
    'agl': 'Agonlin',
    'ahf': 'Ahouandjannafon',
    'aht': 'Akouèhan-Tohoué',
    'agh': 'Agbossa-Adjakahoué',
    'ahl': 'Ahlan',
    'ald': 'Allandohou',
    'alz': 'Allanzounmè',
    'agg': 'Assigui-Gbongodo',
    'asr': 'Assrossa',
    'awd': 'Awogoudo',
    'awn': 'Awonou',
    'dkm': 'Dékanmè',
    'dnn': 'Dannou ',
    'dny': 'Dannou Ayidagbédji',
    'dmc': 'Démè Centre',
    'fnv': 'Fanvi',
    'fly': 'Fonly',
    'ggb': 'Gangban',
    'ggt': 'Gangban Toganhounsa',
    'gbd': 'Gbada',
    'gdk': 'Gbada Kpota',
    'gnn': 'Gbannan',
    'gdo': 'Gbédogo-Oudanou',
    'ggs': 'Gbègbessa',
    'gkj': 'Gbékandji',
    'gla': 'Gla',
    'gg': 'Gogbo',
    'gnh': 'Gounouhoué',
    'gtn': 'Goutin',
    'hd': 'Houèda',
    'hlk': 'Hlankpa',
    'hdg': 'Houédo-Agué',
    'hss': 'Houssa',
    'hdw': 'Houédo-Wo',
    'hns': 'Houinsa',
    'hkk': 'Houèkpa-Kpota',
    'kdn': 'Kindji-Anamè',
    'kdz': 'Kadébou-Zounmè',
    'kkt': 'Kakanitchoé',
    'kby': 'Klogbomey',
    'kts': 'Kpatinsa',
    'kdj': 'Kpodédji',
    'kpt': 'Kpota',
    'kda': 'Kodé – Akpo',
    'kdg': 'Kodé-Agué',
    'kdk': 'Kodé-Gouké',
    'lks': 'Lokossa',
    'lw': 'Lowé',
    'sr': 'Saoro',
    'ssk': 'Sissèkpa',
    'skj': 'Sèkondji',
    'slk': 'Siliko',
    'stk': 'Sokpètinkon',
    'td': 'Todé',
    'tgt': 'Togbota-Agué',
    'tgo': 'Togbota-Oujra',
    'wd': 'Wadon',
    'zgm': 'Zoungbomè',
    'zgd': 'Zoungodo',
  },
  'agg': {
    'agd': 'Agbodjèdo',
    'ahk': 'Aholoukomè',
    'akd': 'Akpadon',
    'akm': 'Akpakomè',
    'akk': 'Akpoloukomè',
    'akj': 'Akodji',
    'avk': 'Aniviékomè',
    'bmb': 'Be’mbè',
    'bma': 'Be’mbèAkpa',
    'dkp': 'Djèkpé',
    'dgk': 'Djigbékomè',
    'dgd': 'Dogodo',
    'dnk': 'Donoukpa',
    'gdj': 'Gbodjè',
    'gss': 'Goussa',
    'hnt': 'Houinta',
    'kdj': 'Kindji',
    'ktk': 'Kintokomè',
    'smy': 'Somayi',
    'skm': 'Sohèkomè',
    'tkm': 'Trankomè',
    'wkm': 'Woundékomè',
    'zvk': 'Zinviékomè',
  },
  'akm': {
    'abg': 'Abogomè ',
    'agh': 'Abogomè-Hlihouè ',
    'agd': 'Agondozoun',
    'adt': 'Agondozoun Tanmè',
    'akk': 'Akpakanmè ',
    'akh': 'Akpro-Hanzounmè ',
    'akm': 'Akpro-Misserété ',
    'ahj': 'Ahouandji',
    'alg': 'Allagba',
    'aml': 'Amouloko',
    'anl': 'Anianlin',
    'blh': 'Blèhouan',
    'dlk': 'Danmè-Lokonon',
    'dnt': 'Danto',
    'dlp': 'Danto les palmiers',
    'gnm': 'Ganmi',
    'gdj': 'Gbèdji',
    'gks': 'Gbakpo-Sèdjè',
    'gkk': 'Gouako-kotoclomè',
    'hzd': 'Houèzounmè-Daho ',
    'ktg': 'Katagon',
    'klt': 'Kiliti',
    'kv': 'Kouvè',
    'kpg': 'Kpogon',
    'gmk': 'Gomè-Doko ',
    'gms': 'Gomè-Sota',
    'hzk': 'Houèzounmè-Kpèvi',
    'kjd': 'Koudjannada',
    'hnl': 'Hounli',
    'knk': 'Kpanou-Kpadé',
    'kpl': 'Kpolè',
    'ouy': 'Ouiya',
    'sga': 'Sogbé-Aligo',
    'tch': 'Tchian',
    'tkm': 'Tohouikanmè',
    'tkh': 'Tokpa-Houété',
    'vnt': 'Vanté',
    'wsg': 'Wayi-Sogbé',
    'shm': 'Sohomey',
    'tkk': 'Tchoukou-Kpèvi',
    'tnm': 'Tanmè',
    'vka': 'Vakon-Adanhou',
    'vkg': 'Vakon-Agatha',
    'vkn': 'Vakon-Anago',
    'ckz': 'Vakon-Azohouè',
    'vkb': 'Vakon-Gbo',
    'vkk': 'Vakon-Kpozoungo',
    'zdj': 'Zoundji',
    'zgm': 'Zoungbomè',
    'zkj': 'Zoungbomè Kpadjrakanmè',
  },
  'avk': {
    'aft': 'Affandji-Tanmè',
    'afk': 'Affomadjè-Kada',
    'agd': 'Agamadin',
    'ags': 'Agbomassè',
    'ahv': 'Ahovo',
    'alw': 'Alawa',
    'avl': 'Avaligbo',
    'bks': 'Bokousso',
    'dgj': 'Dangbodji',
    'dks': 'Danmè-Kpossou',
    'dth': 'Danmè-Tovihoudji',
    'djm': 'Djomon',
    'ggg': 'Gbagla-Ganfan',
    'ggf': 'Gbagla-Ganfan Flonou',
    'ffk': 'Gbagla-Koké',
    'fka': 'Gbakpo-Aclé',
    'gly': 'Gbakpo-Yénou',
    'ggd': 'Gbégodo',
    'gth': 'Gbétchou',
    'gdj': 'Gbodjè',
    'ghg': 'Gbohoungbo',
    'gzm': 'Gbozounmè',
    'hhn': 'Hèhoun',
    'hdk': 'Houédakomè',
    'hl': 'Houéli',
    'hz': 'Houézè',
    'hda': 'Houndomè-Aligo',
    'hng': 'Houngo',
    'hgd': 'Houngon-Djinon',
    'ktk': 'Katé-Kliko',
    'kgm': 'Kogbomè',
    'ktn': 'Kotan',
    'ktl': 'Kouti- Logon',
    'ktr': 'Kouti-Karo',
    'kty': 'Kouti-Yénawa',
    'lhz': 'Latchè-Houèzounmè',
    'lkd': 'Loko-Davè',
    'ltg': ' Lotin-Gbèdjèhouin',
    'ltd': ' Lotin-Gbégodo',
    'ml': 'Malé',
    'mlh': 'Malé-Houngo',
    'onh': 'Ouanho',
    'odj': 'Ouindodji',
    'sd': 'Sado',
    'sdj': ' Sèdjè',
    'sja': ' Sèdjè-Ahovo',
    'skm': ' Sèkanmè',
    'slg': 'Séligon,',
    'tzn': 'Tanzoun',
    'tzb': 'Tanzoun Bliguédé',
    'tkl': 'Tchakla',
    'tkd': 'Tchoukou-Daho',
    'tdj': 'Todèdji',
    'tys': 'Tokpa-Yonhossou',
    'tkp': ' Tokpo',
    'vgn': 'Vagnon',
    'vdn': 'Vodénou',
    'wm': 'Wamon',
    'zng': ' Zounguè',
  },
  'bnu': {
    'abk': 'Abêokouta',
    'adb': 'Adido',
    'afc': 'Affamè-Centre',
    'agn': 'Agbonan',
    'ags': 'Agbosso',
    'agk': 'Agbosso-Kota',
    'ahz': 'Ahouanzonmè',
    'alk': 'Allankpon',
    'ass': 'Assrossa',
    'abt': 'Atchabita',
    'atp': 'Attankpè',
    'avk': 'Avlankanmè',
    'ayg': 'Ayogo',
    'azs': 'Azongbossa',
    'azz': 'Azonzounmè',
    'bnc': 'Bonou-Centre',
    'dmw': 'Damè-Wogon',
    'dss': 'Dasso',
    'ghz': 'Gnanhoui Zounmè',
    'hvg': 'Hounviguè',
    'lks': 'Lokossa',
    'obs': 'Ouébossou',
    'st': 'Sota',
    'stk': 'Sotinkanmè',
    'tvh': 'Tovoh',
    'wvm': 'Wovimè',
    'zm': 'Zomaï',
  },
  'dgb': {
    'ajd': 'Adjido',
    'aff': 'Affio',
    'agt': 'Agbanta',
    'agn': 'Agbonou',
    'agd': 'Agondo',
    'agg': 'Agonguè',
    'akn': 'Akokponawa',
    'akm': 'Akpamè',
    'akv': 'Akpamè Vèvi',
    'alg': 'Aligbo',
    'awd': 'Allanwadan',
    'dm': 'Damè',
    'dgb': 'Dangbo',
    'dgh': 'Dangbo Honmè',
    'dnk': 'Danko',
    'dmd': 'Dèwémè-Daho',
    'gjg': 'Djigbé',
    'dgd': 'Djigbé Houngon',
    'dgl': 'Dogla',
    'dkm': 'Dokomè',
    'fgk': 'Fingninkanmè',
    'gkc': 'Gbéko Centre',
    'gdk': 'Gbéko Dékangbo',
    'gks': 'Gbéko Sioli',
    'gsm': 'Gbèssoumè',
    'ghs': 'Glahounsa',
    'gls': 'Glahounsa Sèmè',
    'htg': 'Hètin-Gléhoué',
    'hts': 'Hètin-Sota',
    'hdj': 'Hondji',
    'hdm': 'Houédomey',
    'hnh': 'Hounhouè',
    'hzn': 'Hozin',
    'ke': 'Ké',
    'ksn': 'Kessounou',
    'kdk': 'Kodékpémè',
    'kdn': 'Kodono',
    'lk': 'Lakè',
    'mtr': 'Mitro',
    'ntk': 'Monnotokpa',
    'shdd': 'Sèho Djigb',
    'sdj': 'Sodji',
    'ths': 'Togbohounso',
    'tkd': 'Tokpa-Koudjote',
    'tov': 'Tovè',
    'wzm': 'Wozounme',
    'ykn': 'Yokon',
    'zng': 'Zounguè',
    'zsl': 'Zounguè Saï Lagare',
    'znt': 'Zount',
  },
  'smk': {
    'all': 'Agbalilamè',
    'agd': 'Agblangandan',
    'agg': 'Agongo',
    'ags': 'Agonsa Gbo',
    'ahl': 'Ahlomè',
    'ahy': 'Aholouyèmè',
    'akk': 'Akpokpota',
    'ayk': 'Ayokpo',
    'dvt': 'Davatin',
    'dja': 'Dja',
    'dfg': 'Djèffa Glégbonou',
    'dfh': 'Djèffa Houédomè',
    'dhg': 'Djèffa Houédomè  Gbago',
    'dkn': 'Djèffa Kowenou',
    'djh': 'Djèho',
    'egm': 'Ekpè Gbédjamè',
    'ekn': 'Ekpè Kanhonnou',
    'ewd': 'Ekpè  Wéchindahomè',
    'ekk': 'Ekpè-Kpécom',
    'ekm': 'Ekpè-Marina',
    'ekp': 'Ekpè-PK10',
    'eks': 'Ekpè-Seyiv',
    'gkd': 'Gbakpodji',
    'ggb': 'Glogbo',
    'ggp': 'Glogbo Plage',
    'gh': 'Goho',
    'gdk': 'Hovidokpo',
    'kdc': 'Kadjacomè',
    'ktn': 'Kétonou',
    'ktt': 'Kétonou Tchinsa',
    'kkk': 'Kpakpakanmè',
    'kgd': 'Kpoguidi',
    'kkd': 'Kraké-Daho',
    'lkk': 'Lokokoukoumè',
    'mdk': 'Moudokomè',
    'oks': 'Okoun-Sèmè',
    'pdg': 'Podji-Agué',
    'pag': 'Podji-Agué Gbago',
    'pms': 'Podji-Missérété',
    'skj': 'Sèkandji',
    'sda': 'Sèkandji Allamandossi',
    'skh': 'Sèkandji Houéyogbé',
    'smv': 'Sèmè-Podj',
    'tcn': 'Tchonv',
    'tva': 'Tchonvi Agbologou',
    'thu': 'Tohouè',
    'tra': 'Torri-Agons',
    'wga': 'Wégbégo-Adiem',
  },
  'adr': {
    'abd': 'Abadago',
    'adg': 'Adjaglo',
    'agl': 'Adjégounlè',
    'ald': 'Adjélémidé',
    'ajd': 'Adjoda',
    'afc': 'Affacha',
    'aff': 'Affessèda',
    'ate': 'Attan-Ewé',
    'aoa': 'Attan-Ouignan-Ayétèdjou',
    'alj': 'Ayéladjou',
    'dgl': 'Dagbla',
    'dhm': 'Danhimè',
    'ddg': 'Djidagba',
    'dgb': 'Dogbo',
    'egb': 'Egbé',
    'ega': 'Egbè-Agbo',
    'fdt': 'Fouditi',
    'ggt': 'Gbagbata',
    'gbn': 'Gbanou',
    'hdm': 'Houédamè',
    'hgd': 'Houéli-Gaba',
    'icg': 'Ichougbo',
    'igb': 'Igba',
    'iga': 'Igbo-Aïdin',
    'igk': 'Igbo-Akporo',
    'ikk': 'Igbo-Ikoko',
    'ogk': 'Igbo-Iroko',
    'igo': 'Igbo-Oro',
    'iki': 'Ikpinlè-Itaraka',
    'iks': 'Ikpinlè-Sèkanmè',
    'iky': 'Ikpinlè-Yénawa',
    'ika': ' Ilako-Abial',
    'imr': ' Imor',
    'ial': 'Ita Aholou',
    'ita': 'Ita-Aro',
    'itb': ' Ita-Bolarinw',
    'ieg': 'Ita-Egbèbi',
    'iea': 'Ita-Egbèbi-Alakporou',
    'ito': 'Ita-Ogou',
    'igg': 'Itchagba-Gbadodo',
    'itg': 'Itchangni',
    'itd': 'Itchèdè',
    'iwk': 'Iwinka',
    'ioi': ' Iwoyé-Oko-Igb',
    'kjl': ' Kadjol',
    'kkk': 'Kokorokèhoun',
    'kpl': 'Kpoulou',
    'kie': 'Kpoulou-Idi-Ekpè',
    'pli': 'Kpoulou-Itchougan',
    'lg': 'Logou',
    'mss': 'Massè',
    'mag': ' Massè-Adjégounl',
    'msb': 'Missèbo',
    'mwb': ' Mowoban',
    'ogf': 'Obanigbé-Fouditi',
    'oko': ' Obèkè-Ouèr',
    'okt': 'Ogoukpatè',
    'ogr': ' Ogour',
    'oke': ' Oké-Oda',
    'okd': ' Oké-Od',
    'pkl': ' Oké-Ol',
    'oka': ' Oko-Akar',
    'okj': ' Oko-Djèguèdi',
    'okf': ' Okoffi',
    'olg': ' Olog',
    'ola': ' Ologo Akpakp',
    'ohj': 'Olohoungbodjè',
    'ogd': 'Ouignan-Gbadodo',
    'owc': ' Owochand',
    'ttk': ' Tatonnonko',
    'ttj': ' Tatonnonkon Jardi',
    'tfo': ' Teffi-Okéïgbal',
    'tff': ' Toff',
    'tw': 'Towi',
    'tbs': 'Troboss',
  },
  'ifg': {
    'ady': 'Adanmayi',
    'agd': 'Agbodjèdo',
    'akj': 'Akadja',
    'aad': 'Akadja-Agamadin',
    'ajg': 'Akadja-Gbodjè ',
    'akg': 'Akadja-Goutèdo ',
    'arm': 'Araromi ',
    'ayj': 'Ayétèdjou ',
    'bgg': 'Banigbé Gare ',
    'bgl': 'Banigbé Lokossa ',
    'bnn': 'Banigbé-Nagot ',
    'bdj': 'Baodjo ',
    'dgd': 'Daagbé-Djèdje',
    'dgn': 'Daagbé-Nagot',
    'dan': 'Dan',
    'dgb': 'Dangban ',
    'dsh': 'Dessah ',
    'dga': 'Djégou-Ayidjèdo',
    'dgj': 'Djégou-Djèdje',
    'dgg': 'Djégou-Nagot',
    'dk': 'Doké ',
    'doh': 'Doké-Hanzoumè',
    'dks': 'oké-Sèdjè',
    'smi': 'Ganmi ',
    'ggb': 'Gblogblo',
    'gga': 'Gblogblo Agbodjèdo',
    'gbk': 'Gbokou ',
    'gkt': 'Gbokoutou ',
    'hg': ' Hègo',
    'hbd': 'Houmbo-Djèdje ',
    'hbg': 'Houmbo-Nagot ',
    'ido': 'Idi-Oro ',
    'ifg': 'Ifangni-Odofin ',
    'igl': 'Igolo ',
    'igg': ' Iguignanhoun',
    'iko': ' Iko',
    'ita': ' Ita-Elèkpètè',
    'itk': ' Ita-Kpako',
    'its': ' Ita-Soumba',
    'iky': ' Iyoko',
    'ktg': 'Kétou Gbécon ',
    'ktk': 'Kétoukpè ',
    'ktb': 'Kitigbo ',
    'kak': 'Ko-Agonkessa ',
    'kag': 'Ko-Anagodo ',
    'kaj': 'Ko-Ayidjèdo ',
    'kdg': 'Ko-Dogba ',
    'kgg': 'Ko-Gbégodo ',
    'ghz': 'Ko-Houézè ',
    'kkl': 'Ko-Koumolou ',
    'kog': 'Ko-Ogou ',
    'kuy': 'Kouyè ',
    'kzd': 'Ko-Zoungodo',
    'lgb': 'Lagbè ',
    'lkk': 'Loko-Koukou',
    'lks': ' Lokossa-Alihogodo',
    'lub': ' Loubé',
    'mng': 'Mongba ',
    'ojr': 'Okédjéré ',
    'oko': ' Oké-Odja',
    'sd': ' Sèdo',
    'sb': 'Sobè ',
    'sba': 'Sobè-Ayelawadjè ',
    'sku': 'Sokou ',
    'ska': 'Sokou-Alihogbogo ',
    'sr': ' Sori ',
    'tmd': 'Tamondo ',
    'tdc': 'Tchaada Centre',
    'zan': ' Zian',
  },
  'ktu': {
    'adk': 'Adakplamè ',
    'adz': 'Adjozounmè ',
    'agk': 'Agonlin-Kpahou ',
    'agz': 'Agozounmè ',
    'agd': 'Aguidi ',
    'agg': 'Aguigadji ',
    'akk': 'Akpakamè ',
    'akb': 'Akpambaou ',
    'ali': 'Alagbé- Illikimoun ',
    'akt': 'Alakouta ',
    'asn': 'Assèna ',
    'atk': 'Atanka ',
    'ato': 'Atan-Ochoukpa ',
    'atb': 'Atchoubi ',
    'awa': 'Awaï ',
    'awy': 'Awaya ',
    'ayt': 'Ayékotonian ',
    'ayk': 'Ayékou ',
    'ayl': 'Ayélawadjè ',
    'ayj': 'Ayétèdjou ',
    'blr': 'Bolorounfè ',
    'dgj': 'Dagbandji ',
    'dog': 'Dogo ',
    'adn': 'Edènou ',
    'eft': 'Effèoutè ',
    'adi': 'Emèda- Igboïloukan ',
    'exe': 'Ewè ',
    'ggg': 'Gangnigon ',
    'gkn': 'Gbaka-Nanzè ',
    'gbg': 'Gbègon ',
    'idj': 'Idadjè ',
    'idn': 'Idéna ',
    'idg': 'Idigny ',
    'ijb': 'Idjabo ',
    'ijj': 'Idjédjé ',
    'iju': 'Idjou ',
    'idf': 'Idoufin ',
    'ige': 'Igbo- Edè ',
    'ebi': 'Igbo-Igannan ',
    'egi': ' Igui-Olou',
    'ikk': 'Ikoko ',
    'ilj': ' Illadji',
    'ilk': ' Illara-Kanga',
    'ilc': ' Illèchin',
    'ilm': ' Illikimoun',
    'ikm': ' Illikimoun-Kolly',
    'ima': 'Imonlè-Ayo ',
    'ins': ' Inansè',
    'idb': ' Iradigban',
    'isb': ' Issèlou',
    'iws': ' Iwéssoun',
    'iwb': ' Iwoyé-Bénin',
    'kjl': ' Kajola',
    'kw': 'Kêwi ',
    'knw': 'Kinwo ',
    'kzv': 'Kozounvi ',
    'kku': ' Kpankou',
    'msf': ' Massafè',
    'mwd': ' Mowodani',
    'obf': ' Obafèmi',
    'otd': ' Obatèdo ',
    'oda': ' Odi- Aro',
    'odk': ' Odokoto',
    'odm': 'Odomèta ',
    'ofi': 'Ofia ',
    'ogl': ' Oguélété',
    'ogg': ' Oguidigbo',
    'ohz': ' Ohizihan',
    'oko': ' Oké-Ola',
    'okt': 'Okpomèta ',
    'olk': 'Oloka',
    'ols': ' Olorounshogo',
    'omu': 'Omou',
    'osk': ' Ossokodjo',
    'sji': ' Sodji',
    'vji': ' Vedji',
    'wrk': ' Woroko',
    'zgi': ' Zounguè-Igboola',
    'zke': ' Zounkpè-Etigbo',
  },
  'pbe': {
    'aba': 'Abba ',
    'adg': 'Adjégounlè ',
    'aji': 'Adjissou ',
    'agl': 'Agbelè ',
    'ahg': 'Ahoyèyè ',
    'akh': 'Akouho ',
    'akm': 'Akpaman ',
    'akt': 'Akpaté ',
    'acg': 'Atchaga ',
    'aya': 'Ayérè-Agbarou ',
    'atj': 'Ayétèdjou ',
    'bng': 'Banigbé ',
    'chf': 'Chaffou ',
    'egl': 'Eguélou ',
    'gng': 'Gbanago ',
    'ibt': 'Ibaté ',
    'ido': 'Idi-Oro ',
    'idg': 'Idogan ',
    'iga': 'Iga ',
    'ign': 'Igana ',
    'igb': 'Igbidi ',
    'igs': 'Igbo-Assogba ',
    'ige': 'Igbo-Edè ',
    'igw': 'Igbo-Ewé ',
    'igc': 'Igboïché ',
    'igl': 'Igbokofin-Eguélou ',
    'igo': 'Igbo-Ocho ',
    'ihr': 'Ihoro ',
    'ilk': 'Illèkpa ',
    'ilm': 'Illèmon ',
    'ilf': 'Illoulofin ',
    'ilo': 'Illoussa-Ossomou ',
    'isb': 'Issaba ',
    'isa': 'Issalè –Affin ',
    'iad': ' Issalè- Affin Douane',
    'ili': 'Issalé-Ibèrè ',
    'ita': 'Ita-Adélèyè ',
    'iag': ' Ita-Atinga',
    'itg': 'Itchagba ',
    'itc': 'Itchakpo ',
    'thd': ' Itchédé',
    'itk': ' Itchéko',
    'ich': ' Itchoché',
    'iwy': ' Iwoyé',
    'kjl': ' Kadjola',
    'ket': ' Ketty',
    'lfw': 'Lafènwa ',
    'mmg': ' Mamagué',
    'ogb': 'Ogouba',
    'oka': ' Oké Ata',
    'oko': ' Oké Ola',
    'oki': 'Oké-Ita,',
    'ong': ' Onigbolo',
    'otk': 'Otèkotan ',
    'ogi': ' Ouignan-Ilé',
    'pbn': ' Pobè-Nord',
    'tll': ' Talala',
    'tw': 'Towé',
  },
  'skt': {
    'ady': 'Adanmayi ',
    'agl': 'Adjégounlè ',
    'adk': 'Adjohoun-Kollé ',
    'akl': 'Adjohoun-Kollédjèdjè ',
    'agh': 'Agada-Hounmè ',
    'ags': 'Agonsa ',
    'akj': 'Akadja ',
    'akc': 'Akpéchi ',
    'arr': 'Araromi ',
    'arm': 'Araromi ',
    'ari': 'Araromi Ita-Akadi ',
    'arb': 'Aribidessi ',
    'asg': 'Assa-Gamè ',
    'asi': 'Assa-Idioché ',
    'aok': 'Attan Okouta-Kadjola ',
    'ato': 'Attan-Onibédji ',
    'atl': 'Attêwo Lara ',
    'aoa': 'Ayétoro Oké Awo ',
    'ayj': 'Ayidjèdo ',
    'ayt': 'Ayita ',
    'brg': 'Barigbo-Owodé ',
    'dgb': 'Dagbao ',
    'dgu': 'Dégoun ',
    'dge': 'Dèguè ',
    'dko': 'Djoko ',
    'dra': 'Dra ',
    'gbn': 'Gbagla Nounagnon ',
    'gyd': 'Gbagla-Yovogbédji ',
    'gkd': 'Gbokoudaï ',
    'gbt': 'Gbougbouta ',
    'gom': 'Gbozounmon ',
    'hgo': 'Houègbo ',
    'hnm': 'Hounmè ',
    'ibs': 'Ibadja Sodji ',
    'ijb': 'Idjiboro ',
    'iga': 'Igba ',
    'igs': 'Igbo- Assan ',
    'igg': 'Igbo Egan ',
    'igb': 'Igbo-Abikou ',
    'iak': 'Igbo-Akpa ',
    'ibe': 'Igbo-Eyê ',
    'igl': 'Igbola ',
    'ikm': ' Ikêmon',
    'ikj': 'Ikpédjilé ',
    'ikf': ' Illako Faadji-Ita AKpinty',
    'iki': ' Illako  Idioro',
    'isn': 'Illasso Nagot ',
    'iss': 'Illasso Saharo ',
    'ila': ' Illoro Aguidi',
    'ilk': ' Illougou-Kossomi',
    'ise': 'Issalè Eko ',
    'ita': ' Ita Alabè',
    'itg': 'Ita Gbokou ',
    'ioi': 'Ita Oro-Irédé ',
    'ity': ' Ita-Ayinla',
    'iwr': ' Iwéré',
    'kjl': ' Kadjola',
    'kjb': ' Kobèdjo',
    'kgm': ' Kologbo Mèkè',
    'kss': ' Kossi',
    'mkp': ' Makpa',
    'mkh': ' Makpohou',
    'mdg': ' Modogan',
    'mr': ' Moro',
    'odr': 'Odanrégoun ',
    'ody': ' Odanyogoun',
    'odl': ' Odella',
    'oke': ' Oké',
    'okg': 'Okéïgbo ',
    'shd': 'Saharo Djèdjè ',
    'shn': 'Saharo Nagot ',
    'snk': 'Sanrin-Kpinlè ',
    'sji': ' Sodji',
    'srl': ' Suru Léré',
    'tkc': ' Takon Centre',
    'tot': ' Tota',
    'wai': 'Waï ',
    'ygt': ' Yogou Tohou',
    'ykc': ' Yoko Centre',
    'zmn': ' Zimon',
  },
  'aby': {
    'adj': 'Adandokpodji',
    'agm': 'Agblomè',
    'agg': 'Agbodjannangan',
    'agn': 'Agnangnan',
    'ahg': 'Ahouaga',
    'aks': 'Akouessa',
    'amk': 'Allomakanmè',
    'azl': 'Azali',
    'dtc': 'Détohou Centre',
    'dlt': 'Dilikotcho',
    'djg': 'Djègbé',
    'djm': 'Djimè',
    'dgm': 'Doguèmè',
    'dk': 'Dokon',
    'dt': 'Dota',
    'gbh': 'Gbècon-Houégbo',
    'gzk': 'Gbèhizankon',
    'gkh': 'Gbèkon Hounli',
    'gst': 'Gnansata',
    'gh': 'Goho',
    'ggg': 'Guèguèzogon',
    'hua': 'Houao',
    'hul': 'Houéli',
    'htj': 'Hountondji',
    'kjc': 'Kodji Centre',
    'lgh': 'Lègbaholi',
    'll': 'Lèlè',
    'lkk': 'Lokokanmè',
    'uem': 'Ouémè',
    'sad': 'Sad',
    'shu': 'Sèhou',
    'sga': 'Sogbo-Aliho',
    'she': 'Sohouè',
    'sna': 'Sonou Akouta',
    'snf': 'Sonou Fiy',
    'thl': 'Tohizanly',
    'vkp': 'Vèkpa',
    'wnk': 'Wankon',
    'wtg': 'Wo-Tangadj',
    'zss': 'Zass',
    'zzm': 'Zounzonm',
  },
  'agh': {
    'abg': 'Abigo',
    'adj': 'Adanhondjigon',
    'adn': 'Adingnigon',
    'ajd': 'Adjido',
    'agz': 'Agbangnizoun',
    'agd': 'Agbidimè',
    'ahg': 'Ahissatogon',
    'akm': 'Ahouakanmè',
    'adb': 'Akodébakou',
    'akd': 'Akpého-Dokpa',
    'ahs': 'Akpého-Sèmè',
    'avl': 'Avali',
    'akp': 'Azankpanto',
    'azz': 'Azozoundji',
    'dnl': 'Danli',
    'dkm': 'Dékanmè',
    'dlf': 'Dilly-Fanou',
    'dji': 'Dodji',
    'ddm': 'Dodomè',
    'fnl': 'Fonli',
    'gdm': 'Gbindounmè',
    'gbl': 'Gboli',
    'gb1': 'Gbozoun 1',
    'gb2': 'Gbozoun 2',
    'gzt': 'Gnizinta',
    'hgd': 'Hagbladou',
    'hja': 'Hodja',
    'hal': 'Houala',
    'hnl': 'Houndo',
    'hnt': 'Hounto',
    'knz': 'Kanzoun',
    'ktm': 'Kpatinmè',
    'kji': 'Kpodji',
    'kpt': 'Kpota',
    'kpo': 'Kpoto',
    'leg': 'Lèg',
    'lsz': 'Lissazounmè',
    'lkp': 'Loukpé',
    'mkg': 'Makpéhogon',
    'mgh': 'Mignonhito',
    'ogn': 'Oungbènoudo',
    'skt': 'Sèkidjato',
    'shd': 'Sohouè-Dovot',
    'tgd': 'Tangoudo',
    'tnt': 'Tanta',
    'tnv': 'Tanvè',
    'tkp': 'Tokpa',
    'tst': 'Tossota',
    'twt': 'Towéta',
    'wje': 'Wèdjè',
    'zgb': 'Zoungbo-Gblom',
    'zgd': 'Zoungoud',
    'znm': 'Zounmè',
  },
  'bhc': {
    'adl': 'Adagamè-Lisèzoun ',
    'adm': 'Adamè ',
    'ada': 'Adamè-Adato ',
    'adh': 'Adamè-Ahito ',
    'amk': 'Adanminakougon ',
    'adg': 'Agbadjagon ',
    'agg': 'Agbangon ',
    'awm': 'Agbanwémè ',
    'agk': 'Agbokou ',
    'agz': 'Agonvèzoun ',
    'ahd': 'Ahouadanou ',
    'ahl': 'Ahouali ',
    'ahm': 'Ahouamè ',
    'aht': 'Ahouamè-Ahito ',
    'awe': 'Aïwémè ',
    'alg': 'Aligoudo ',
    'alk': 'Alikpa ',
    'acm': 'Atchonmè ',
    'atg': 'Attogouin ',
    'dkp': 'Dakpa ',
    'dsh': 'Djèssouhogon ',
    'dgb': 'Djognangbo ',
    'dnt': 'Djonouta ',
    'dko': 'Dokon ',
    'egm': 'Edjêgbinmêgon ',
    'fli': 'Fléli ',
    'gcp': 'Gancon-Ponsa ',
    'ghc': 'Gbanhicon ',
    'gbt': 'Gbéto ',
    'gdz': 'Gnidjazoun',
    'hlu': 'Hélou ',
    'hzh': 'Hèzonho ',
    'hmh': 'Honmèho ',
    'hnd': 'Houndon ',
    'hdo': 'Houndonho ',
    'kdt': 'Kodota ',
    'ktl': ' Kpatalocoli',
    'kpo': 'Kpocon ',
    'lsz': 'Lissèzoun',
    'ldv': 'Lokodavè ',
    'lkz': 'Lokozoun ',
    'lto': 'Lotcho ',
    'mde': 'Madjè ',
    'mnb': 'Manaboè ',
    'msg': 'Massè-Gbamè ',
    'osh': 'Ouassaho ',
    'ssk': 'Saclo – Sokon',
    'slk': 'Saclo-Alikpa ',
    'shh': ' Sèhouèho',
    'sm': ' Sèmè',
    'slh': ' Siliho ',
    'sdh': 'Sodohomè ',
    'sgb': ' Sogba ',
    'skd': 'Sokpadelli ',
    'tdd': 'Todo ',
    'tvg': 'Tovigomè',
    'vhu': 'Vèhou ',
    'vll': 'Volli ',
    'wgs': 'Wangnassa ',
    'zkm': 'Zakanmè ',
    'zka': ' Zakpo-Agadamè',
    'zgd': 'Zoungoudo ',
    'zgu': 'Zoungoudo,',
    'zkt': ' Zounkpa-Agbotogon',
    'zzm': 'Zounzonmè',
    'zzs': 'Zounzonsa ',
  },
  'cve': {
    'aby': 'Abayahoué ',
    'aja': 'Adja ',
    'aga': 'Aga ',
    'agh': 'Agbangnanhoué ',
    'agg': 'Agnangan ',
    'ags': 'Agossouhoué ',
    'aht': 'Ahito ',
    'azd': 'Aïzondo ',
    'akt': 'Akpatchihoué ',
    'atg': 'Attogon ',
    'azh': 'Azéhounholi ',
    'azl': 'Azonholi ',
    'bgn': 'Bagon ',
    'dhe': 'Dahoué ',
    'dhg': 'Dahouigon ',
    'dgh': 'Dangbéhonou ',
    'dkd': 'Dekpada ',
    'dm': 'Domè ',
    'fng': 'Finangnon ',
    'fnl': 'Fonli ',
    'gdh': 'Gandahogon ',
    'het': 'Houeton ',
    'hyh': 'Houeyiho',
    'hnd': 'Houndo ',
    'hnl': 'Hounholi ',
    'hvg': 'Hounviguèli ',
    'kgd': 'Kpagoudo',
    'mkg': 'Makpegon',
    'sjk': 'Sekon-Djakpa ',
    'ssm': 'Sèslamè ',
    'tue': 'Toué',
    'vm': 'Vèmè',
    'vl': 'Voli ',
    'ynw': 'Yénawa ',
    'zgl': 'Zogoli',
    'zgd': 'Zoungoudo',
    'zsg': 'Zounsègo',
  },
  'djj': {
    'adm': 'Adamè ',
    'adh': 'Adamè-Houeglo ',
    'agk': 'Agblokpa ',
    'agt': 'Agbohoutogon ',
    'agd': 'Agondokpoé ',
    'agh': 'Agonhohoun ',
    'aht': 'Ahito ',
    'ahk': 'Ahokanmè ',
    'ahz': 'Ahozoun ',
    'ahj': 'Aïhouidji ',
    'akl': 'Aklinmè ',
    'amk': 'Amakpa ',
    'amt': 'Amontika ',
    'asn': 'Assan ',
    'ast': 'Assantoun ',
    'avk': 'Avokanzoun ',
    'awt': 'Awotrele ',
    'ayb': 'Ayogbé ',
    'btt': 'Betta ',
    'bhu': 'Bohoué ',
    'bku': 'Bookou ',
    'chi': 'Chié ',
    'ank': 'Daanon-Kpota ',
    'dan': 'Dan ',
    'dlk': 'Danmlonkou ',
    'den': 'Dénou ',
    'djs': 'Djessi ',
    'dja': 'Djidja-Aligoudo ',
    'djh': 'Djoho ',
    'dkd': 'Djrékpédji ',
    'dhm': 'Dohouimè ',
    'dn': 'Dona ',
    'dji': 'Dridji ',
    'fkm': 'Fonkpamè ',
    'fnj': 'Fonkpodji ',
    'gng': 'Gangan ',
    'gdg': 'Gbadagba ',
    'ghg': 'Gbihoungon ',
    'gbx': 'Gobaix ',
    'gnk': 'Gounoukouin ',
    'gth': 'Goutchon ',
    'hng': 'Hanagbo ',
    'hv': 'Hevi ',
    'hnh': 'Honhoun ',
    'hkp': 'Houkpa ',
    'hnv': 'Hounvi ',
    'hut': 'Houto ',
    'hsh': 'Kassèhlo ',
    'ktk': 'Katakènon ',
    'kg': 'Kingbè ',
    'khg': 'Kohougon ',
    'kk': 'Kokoroko ',
    'km': 'Komè ',
    'kkm': 'Kouékouékanmè ',
    'kgj': 'Kougbadji ',
    'ktg': 'Koutagba ',
    'knn': 'Kpakpanènè ',
    'kta': 'Kpétèta ',
    'lgd': 'Lagbado ',
    'lkp': 'Lakpo',
    'lal': 'Lalo ',
    'lad': 'Lèlè-Adato ',
    'lsl': 'Linsinlin ',
    'lbt': 'Lobeta ',
    'lca': 'Lotcho-Ahouamè ',
    'ltd': 'Lotcho-Daho ',
    'mdv': 'Madjavi ',
    'mgs': 'Magassa ',
    'msr': 'Monsourou ',
    'mga': 'Mougnon-Aké ',
    'mgk': 'Mougnon-Kossou ',
    'ndg': 'Nontchédigbé ',
    'slj': 'Saloudji ',
    'skt': 'Sankpiti ',
    'svk': 'Savakon',
    'swk': ' Sawlakpa',
    'stt': 'Setto ',
    'svg': ' Sovlegni',
    'szn': 'Sozoun ',
    'tnh': 'Tannouho',
    'tkg': 'Tokégon ',
    'tkk': 'ToKounkoun',
    'tkp': 'Tokpé ',
    'tst': 'Tossota',
    'vev': 'Vévi ',
    'wgy': ' Wogbaye',
    'wku': 'Wokou',
    'yng': 'Yagbanougon',
    'ye': ' Yè',
    'zdk': 'Zadakon',
    'zkn': ' Zakan',
    'zkm': ' Zinkanmè',
    'zgh': ' Zoungahou',
    'znk': 'Zounkon ',
    'znm': 'Zounmè',
  },
  'onh': {
    'adm': 'Adamè ',
    'adg': 'Adogon ',
    'agk': 'Agonkon ',
    'ahc': 'Ahicon ',
    'ahg': 'Ahogo ',
    'aze': 'Aïzè ',
    'akz': 'Akantè Zaloko ',
    'atz': 'Akantè Zoungo ',
    'aks': 'Akassa ',
    'ald': 'Allabandé ',
    'bsk': 'Bossa Kpota ',
    'bst': 'Bossa Togoudo ',
    'bkd': 'Dokodji ',
    'dlv': 'Dolivi ',
    'gku': 'Gakou ',
    'ggb': 'Gangban ',
    'ghm': 'Ganhounmè ',
    'gkg': 'Gbokpago ',
    'gnl': 'Gnanli ',
    'hvd': 'Hinvédo ',
    'hli': 'Holli ',
    'hdj': 'Houaidja ',
    'hnv': 'Houanvè ',
    'hed': 'Houédja ',
    'hnm': 'Hounnoumè ',
    'iko': 'Ilaka- Ozokpodji ',
    'ksd': 'Kinsodji ',
    'khs': 'Kolly-Houssa ',
    'mfg': 'Manfougbon ',
    'mng': 'Midjannangnan',
    'mzg': ' Monzoungoudo',
    'oid': 'Odja-Idossou ',
    'oka': ' Ouokon-Ahlan',
    'okz': ' Ouokon-Zoungomè',
    'oss': 'Oussa ',
    'tnu': 'Tannou ',
    'tvd': ' Tévêdji',
    'tzg': 'Tozoungo ',
    'ygo': ' Yaago',
    'zng': ' Zounguè',
  },
  'zkp': {
    'adm': 'Adamè ',
    'adw': 'Adawémè ',
    'adk': 'Adikogon ',
    'ajd': 'Adjido ',
    'ajk': 'Adjokan ',
    'adj': 'Adjoko ',
    'addv': 'Adovi ',
    'afs': 'Affossowogba ',
    'agk': 'Agbakou ',
    'agg': 'Agbogbomey ',
    'agp': 'Agbokpa ',
    'agd': 'Agondokpoé ',
    'agb': 'Agongbo ',
    'agm': 'Agonkanmè ',
    'ahs': 'Ahossougon ',
    'atk': 'Aïtèdékpa ',
    'akj': 'Akadjamè ',
    'akt': 'Akètèkpa ',
    'alh': 'Allahé ',
    'alg': 'Alligoudo ',
    'ahj': 'Amlihohoué-Jardin ',
    'asl': 'Assanlin ',
    'dgn': 'Dangbégon ',
    'ddt': 'Dantota ',
    'dvg': 'Davègo ',
    'dtk': 'Dètèkpa ',
    'dtn': 'Djoïtin ',
    'dgl': 'Dogbanlin ',
    'dkp': 'Dokpa ',
    'dt': 'Dotan ',
    'dut': 'Doutin ',
    'drm': 'Dramè ',
    'fll': 'Folly ',
    'gnh': 'Ganhoua ',
    'gdk': 'Gnadokpa ',
    'hhl': 'Hêhounli ',
    'hng': 'Houangon ',
    'hlk': 'Houanlikpa ',
    'hkm': 'Houkanmè ',
    'hgm': 'Houngomè ',
    'kmj': 'Kèmondji ',
    'keo': 'Kéou ',
    'kdt': ' Kodota',
    'kgd': 'Koguédé ',
    'kkm': 'Kpakpamè ',
    'kks': 'Kpakpassa ',
    'kkp': 'Kpokpoé',
    'klk': 'Kpolokoé ',
    'lkl': 'Lokoli ',
    'ltk': 'Lontonkpa ',
    'mgg': 'Mlinkpin-Guingnin ',
    'sgl': ' Sogbèlankou',
    'shg': 'Sohoungo ',
    'sht': ' Sohounta',
    'sm': 'Somè ',
    'swk': 'Sowékpa ',
    'tgb': 'Tangbé ',
    'tnt': ' Tanta',
    'tgj': 'Togadji ',
    'ydn': 'Yadin ',
    'yhe': ' Yohouè',
    'zag': ' Za-Aga',
    'zah': 'Za-Hla',
    'zkk': ' Za-Kékéré',
    'zkp': ' Za-Kpota',
    'zzm': ' Za-Zounmè',
    'zek': 'Zéko',
    'zgd': ' Zoungoudo',
    'zzn': 'Zounzonmè',
  },
  'zgd': {
    'agh': 'Agbladoho ',
    'agg': 'Agongbodji ',
    'agv': 'Agonvè ',
    'ahl': 'Ahlan ',
    'akh': 'Akohagon ',
    'asg': 'Assiangbomè ',
    'ayg': 'Ayogo ',
    'azk': 'Azakpa ',
    'bme': 'Bamè ',
    'dzg': 'Dizigo ',
    'dga': 'Doga-Aga ',
    'dgl': 'Doga-Alikon ',
    'dgd': 'Doga-Domè ',
    'dhm': 'Dohounmè ',
    'dal': 'Don-Aliho ',
    'dth': 'Don-Tohomè ',
    'dv': 'Dovè ',
    'gtz': 'Gbatèzounmè ',
    'gbn': 'Gbonou ',
    'glj': 'Goblidji ',
    'hba': 'Houégbo-Aga ',
    'hgd': 'Houégbo-Do ',
    'kgn': 'Kingon ',
    'klb': 'Klobo ',
    'kpt': 'Kpoto ',
    'lgd': 'Lègbado ',
    'lka': 'Loko-Alankpé ',
    'msg': 'Massagbo ',
    'ndk': 'N’Dokpo ',
    'sgv': 'Sagbovi ',
    'sw': 'Sowé ',
    'taj': 'Tan-Adja ',
    'thg': 'Tan-Houègbo',
    'tkg': 'Tokplégbé ',
    'vod': 'Vodo ',
    'wmt': 'Womèto ',
    'zgd': 'Zagnanado ',
    'zio': 'Zantan- Igbo-Ola',
    'zng': 'Zingon ',
    'znm': 'Zonmon ',
    'zgu': 'Zoungoudo',
    'zwk': 'Zoungo-Wokpa',
    'znu': 'Zounnou ',
  },
  'zdy': {
    'agd': 'Agbladaho',
    'agg': 'Agongbodji',
    'agv': 'Agonvè',
    'ahl': 'Ahlan',
    'akh': 'Akohagon',
    'ass': 'Assiangbome',
    'ayg': 'Ayogo',
    'azk': 'Azakpa',
    'bm': 'Bame',
    'dzg': 'Dizigo',
    'dga': 'Doga-Aga',
    'dlk': 'Doga-Alikon',
    'dgd': 'Doga-Dome',
    'dhm': 'Dohounme',
    'dlh': 'Don-Aliho',
    'dtm': 'Don-ohome',
    'dv': 'Dove',
    'gtz': 'Gbatezounme',
    'gbn': 'Gbonou',
    'gbd': 'Goblidji',
    'hga': 'Houegbo-Aga',
    'hgd': 'Houegbo-Do',
    'kgn': 'Kingon',
    'klb': 'Klobo',
    'kpt': 'Kpoto',
    'lgd': 'Legbado',
    'lka': 'Loko-Alankpa',
    'msg': 'Massagbo',
    'ndk': "N'Dokpo",
    'sgb': 'Sagbovi',
    'sw': 'Sowe',
    'tad': 'Tan-Adja',
    'tgh': 'Tan-Houegbo',
    'vod': 'Vodo',
    'wmt': 'Wometo',
    'zgd': 'Zagnanado',
    'zio': 'Zantan-Igbo-Ola',
    'zgn': 'Zingnon',
    'znm': 'Zonmon',
    'zwk': 'Zounmon-Wokpa',
    'znd': 'Zoungoudo',
    'zum': 'Zounmon',
  }
};
