Map<String, String> department = {
  // 'alb': 'Alibori',
  // 'atc': 'Atacora',
  // 'Atl': 'Atlantique',
  // 'brg': 'Borgou',
  // 'cln': 'Collines',
  // 'kff': 'Kouffo',
  // 'dng': 'Donga',
  // 'ltr': 'Littoral',
  // 'mn': 'Mono',
  'ome': 'Ouémé',
  'plt': 'Plateau',
  'zou': 'Zou',
};
Map<String, Map<String, String>> common = {
  'ome': {
    'ajr': 'Adjarra',
    'ajh': 'Adjohoun',
    'agg': 'Aguégués',
    'akm': 'AkpoMissérété',
    'avk': 'Avrankoun',
    'bnu': 'Bonou',
    'dgb': 'Dangbo',
    'smk': 'Sèmè-Kpodji'
  },
  'plt': {
    'adr': 'Adja-Ouèrè',
    'ifg': 'Ifangni',
    'ktu': 'Kétou',
    'pbe': 'Pobè',
    'skt': 'Sakété',
  },
  'zou': {
    'aby': 'Abomey',
    'agh': 'Agbangnizoun',
    'bhc': 'Bohicon',
    'cve': 'Cove',
    'djj': 'Djidja',
    'onh': 'Ouinhi',
    'zkp': 'Zakpota',
    'zgd': 'Zangnanado',
    'zdy': 'Zogbodomey'
  },
};

Map<String, Map<String, String>> district = {
  'ajr': {
    'adv': 'Adovié',
    'adg': 'Adovié Alaga',
    'adj': 'Adjinan',
    'adn': 'Adjinan-Aga',
    'adh': 'Adjati-Djogbèhouè',
    'adt': 'Adjati-vèdo',
    'agg': 'Agaougbéta',
    'aga': 'Agata',
    'atp': 'Agbomey-Takplikpo',
    'agt': 'Agaougbéta',
    'abt': 'Agboto',
    'agl': 'Aglogbè',
    'ayz': 'Ayihounzo',
    'alk': 'Alladako',
    'ald': 'Alladako-Dégoèto',
    'ang': 'Anagbo',
    'bkv': 'Bokovi-Tchaka',
    'djv': 'Djavi',
    'djz': 'Djavi-Zèbè',
    'djw': 'Djèvié -Wadon',
    'dhg': 'Do-Hongla',
    'dav': 'Dossouvié',
    'dgb': 'Drogbo',
    'gsk': 'Gassako',
    'ggt': 'Gbangnito',
    'ghy': 'Gbéhamey',
    'hhm': 'Hahamè',
    'hvk': 'Hêvié-Kpota',
    'hgb': 'Houêgbo',
    'hhk': 'Hounhouèko',
    'hgs': 'Hounsa-Assiogbossa',
    'hsv': 'Hounsinvié',
    'hnv': 'Hounvè',
    'hvc': 'Honvié Centre',
    'kpt': 'Kpota',
    'ldg': 'Lindja-Dangbo',
    'kdv': 'Kpadovié',
    'kvd': 'Kpovié-Gbada',
    'mlh': 'Malanhoui',
    'mkd': 'Malanhoui-Kpodo',
    'mdj': 'Médédjonou',
    'mdg': 'Mèdédjonou-Gbéhadji',
    'ouk': 'Ouèkè',
    'sdj': 'Sèdjè',
    'sm': 'Sèmè',
    'sgt': 'Sèdjè-Gbéta',
    'st': 'Sota',
    'stt': 'Sota-Tchémè',
    'tnm': 'Tanmè',
    'thk': 'Tchakou',
    'tkm': 'Tokomè',
    'vjn': 'Vidjinan',
    'yv': 'Yèvié',
  },
  'ajh': {
    'abt': 'Abato',
    'akt': 'Abéokouta',
    'abd': 'Abidomey',
    'agk': 'Agbakon',
    'agm': 'Agué-Milahin',
    'agl': 'Agonlin',
    'ahf': 'Ahouandjannafon',
    'aht': 'Akouèhan-Tohoué',
    'agh': 'Agbossa-Adjakahoué',
    'ahl': 'Ahlan',
    'ald': 'Allandohou',
    'alz': 'Allanzounmè',
    'agg': 'Assigui-Gbongodo',
    'asr': 'Assrossa',
    'awd': 'Awogoudo',
    'awn': 'Awonou',
    'dkm': 'Dékanmè',
    'dnn': 'Dannou ',
    'dny': 'Dannou Ayidagbédji',
    'dmc': 'Démè Centre',
    'fnv': 'Fanvi',
    'fly': 'Fonly',
    'ggb': 'Gangban',
    'ggt': 'Gangban Toganhounsa',
    'gbd': 'Gbada',
    'gdk': 'Gbada Kpota',
    'gnn': 'Gbannan',
    'gdo': 'Gbédogo-Oudanou',
    'ggs': 'Gbègbessa',
    'gkj': 'Gbékandji',
    'gla': 'Gla',
    'gg': 'Gogbo',
    'gnh': 'Gounouhoué',
    'gtn': 'Goutin',
    'hd': 'Houèda',
    'hlk': 'Hlankpa',
    'hdg': 'Houédo-Agué',
    'hss': 'Houssa',
    'hdw': 'Houédo-Wo',
    'hns': 'Houinsa',
    'hkk': 'Houèkpa-Kpota',
    'kdn': 'Kindji-Anamè',
    'kdz': 'Kadébou-Zounmè',
    'kkt': 'Kakanitchoé',
    'kby': 'Klogbomey',
    'kts': 'Kpatinsa',
    'kdj': 'Kpodédji',
    'kpt': 'Kpota',
    'kda': 'Kodé – Akpo',
    'kdg': 'Kodé-Agué',
    'kdk': 'Kodé-Gouké',
    'lks': 'Lokossa',
    'lw': 'Lowé',
    'sr': 'Saoro',
    'ssk': 'Sissèkpa',
    'skj': 'Sèkondji',
    'slk': 'Siliko',
    'stk': 'Sokpètinkon',
    'td': 'Todé',
    'tgt': 'Togbota-Agué',
    'tgo': 'Togbota-Oujra',
    'wd': 'Wadon',
    'zgm': 'Zoungbomè',
    'zgd': 'Zoungodo',
  },
  'agg': {
    'agd': 'Agbodjèdo',
    'ahk': 'Aholoukomè',
    'akd': 'Akpadon',
    'akm': 'Akpakomè',
    'akk': 'Akpoloukomè',
    'akj': 'Akodji',
    'avk': 'Aniviékomè',
    'bmb': 'Be’mbè',
    'bma': 'Be’mbèAkpa',
    'dkp': 'Djèkpé',
    'dgk': 'Djigbékomè',
    'dgd': 'Dogodo',
    'dnk': 'Donoukpa',
    'gdj': 'Gbodjè',
    'gss': 'Goussa',
    'hnt': 'Houinta',
    'kdj': 'Kindji',
    'ktk': 'Kintokomè',
    'smy': 'Somayi',
    'skm': 'Sohèkomè',
    'tkm': 'Trankomè',
    'wkm': 'Woundékomè',
    'zvk': 'Zinviékomè',
  },
  'akm': {
    'abg': 'Abogomè ',
    'agh': 'Abogomè-Hlihouè ',
    'agd': 'Agondozoun',
    'adt': 'Agondozoun Tanmè',
    'akk': 'Akpakanmè ',
    'akh': 'Akpro-Hanzounmè ',
    'akm': 'Akpro-Misserété ',
    'ahj': 'Ahouandji',
    'alg': 'Allagba',
    'aml': 'Amouloko',
    'anl': 'Anianlin',
    'blh': 'Blèhouan',
    'dlk': 'Danmè-Lokonon',
    'dnt': 'Danto',
    'dlp': 'Danto les palmiers',
    'gnm': 'Ganmi',
    'gdj': 'Gbèdji',
    'gks': 'Gbakpo-Sèdjè',
    'gkk': 'Gouako-kotoclomè',
    'hzd': 'Houèzounmè-Daho ',
    'ktg': 'Katagon',
    'klt': 'Kiliti',
    'kv': 'Kouvè',
    'kpg': 'Kpogon',
    'gmk': 'Gomè-Doko ',
    'gms': 'Gomè-Sota',
    'hzk': 'Houèzounmè-Kpèvi',
    'kjd': 'Koudjannada',
    'hnl': 'Hounli',
    'knk': 'Kpanou-Kpadé',
    'kpl': 'Kpolè',
    'ouy': 'Ouiya',
    'sga': 'Sogbé-Aligo',
    'tch': 'Tchian',
    'tkm': 'Tohouikanmè',
    'tkh': 'Tokpa-Houété',
    'vnt': 'Vanté',
    'wsg': 'Wayi-Sogbé',
    'shm': 'Sohomey',
    'tkk': 'Tchoukou-Kpèvi',
    'tnm': 'Tanmè',
    'vka': 'Vakon-Adanhou',
    'vkg': 'Vakon-Agatha',
    'vkn': 'Vakon-Anago',
    'ckz': 'Vakon-Azohouè',
    'vkb': 'Vakon-Gbo',
    'vkk': 'Vakon-Kpozoungo',
    'zdj': 'Zoundji',
    'zgm': 'Zoungbomè',
    'zkj': 'Zoungbomè Kpadjrakanmè',
  },
  'avk': {
    'aft': 'Affandji-Tanmè',
    'afk': 'Affomadjè-Kada',
    'agd': 'Agamadin',
    'ags': 'Agbomassè',
    'ahv': 'Ahovo',
    'alw': 'Alawa',
    'avl': 'Avaligbo',
    'bks': 'Bokousso',
    'dgj': 'Dangbodji',
    'dks': 'Danmè-Kpossou',
    'dth': 'Danmè-Tovihoudji',
    'djm': 'Djomon',
    'ggg': 'Gbagla-Ganfan',
    'ggf': 'Gbagla-Ganfan Flonou',
    'ffk': 'Gbagla-Koké',
    'fka': 'Gbakpo-Aclé',
    'gly': 'Gbakpo-Yénou',
    'ggd': 'Gbégodo',
    'gth': 'Gbétchou',
    'gdj': 'Gbodjè',
    'ghg': 'Gbohoungbo',
    'gzm': 'Gbozounmè',
    'hhn': 'Hèhoun',
    'hdk': 'Houédakomè',
    'hl': 'Houéli',
    'hz': 'Houézè',
    'hda': 'Houndomè-Aligo',
    'hng': 'Houngo',
    'hgd': 'Houngon-Djinon',
    'ktk': 'Katé-Kliko',
    'kgm': 'Kogbomè',
    'ktn': 'Kotan',
    'ktl': 'Kouti- Logon',
    'ktr': 'Kouti-Karo',
    'kty': 'Kouti-Yénawa',
    'lhz': 'Latchè-Houèzounmè',
    'lkd': 'Loko-Davè',
    'ltg': ' Lotin-Gbèdjèhouin',
    'ltd': ' Lotin-Gbégodo',
    'ml': 'Malé',
    'mlh': 'Malé-Houngo',
    'onh': 'Ouanho',
    'odj': 'Ouindodji',
    'sd': 'Sado',
    'sdj': ' Sèdjè',
    'sja': ' Sèdjè-Ahovo',
    'skm': ' Sèkanmè',
    'slg': 'Séligon,',
    'tzn': 'Tanzoun',
    'tzb': 'Tanzoun Bliguédé',
    'tkl': 'Tchakla',
    'tkd': 'Tchoukou-Daho',
    'tdj': 'Todèdji',
    'tys': 'Tokpa-Yonhossou',
    'tkp': ' Tokpo',
    'vgn': 'Vagnon',
    'vdn': 'Vodénou',
    'wm': 'Wamon',
    'zng': ' Zounguè',
  },
  'bnu': {
    'abk': 'Abêokouta',
    'adb': 'Adido',
    'afc': 'Affamè-Centre',
    'agn': 'Agbonan',
    'ags': 'Agbosso',
    'agk': 'Agbosso-Kota',
    'ahz': 'Ahouanzonmè',
    'alk': 'Allankpon',
    'ass': 'Assrossa',
    'abt': 'Atchabita',
    'atp': 'Attankpè',
    'avk': 'Avlankanmè',
    'ayg': 'Ayogo',
    'azs': 'Azongbossa',
    'azz': 'Azonzounmè',
    'bnc': 'Bonou-Centre',
    'dmw': 'Damè-Wogon',
    'dss': 'Dasso',
    'ghz': 'Gnanhoui Zounmè',
    'hvg': 'Hounviguè',
    'lks': 'Lokossa',
    'obs': 'Ouébossou',
    'st': 'Sota',
    'stk': 'Sotinkanmè',
    'tvh': 'Tovoh',
    'wvm': 'Wovimè',
    'zm': 'Zomaï',
  },
  'dgb': {
    'ajd': 'Adjido',
    'aff': 'Affio',
    'agt': 'Agbanta',
    'agn': 'Agbonou',
    'agd': 'Agondo',
    'agg': 'Agonguè',
    'akn': 'Akokponawa',
    'akm': 'Akpamè',
    'akv': 'Akpamè Vèvi',
    'alg': 'Aligbo',
    'awd': 'Allanwadan',
    'dm': 'Damè',
    'dgb': 'Dangbo',
    'dgh': 'Dangbo Honmè',
    'dnk': 'Danko',
    'dmd': 'Dèwémè-Daho',
    'gjg': 'Djigbé',
    'dgd': 'Djigbé Houngon',
    'dgl': 'Dogla',
    'dkm': 'Dokomè',
    'fgk': 'Fingninkanmè',
    'gkc': 'Gbéko Centre',
    'gdk': 'Gbéko Dékangbo',
    'gks': 'Gbéko Sioli',
    'gsm': 'Gbèssoumè',
    'ghs': 'Glahounsa',
    'gls': 'Glahounsa Sèmè',
    'htg': 'Hètin-Gléhoué',
    'hts': 'Hètin-Sota',
    'hdj': 'Hondji',
    'hdm': 'Houédomey',
    'hnh': 'Hounhouè',
    'hzn': 'Hozin',
    'ke': 'Ké',
    'ksn': 'Kessounou',
    'kdk': 'Kodékpémè',
    'kdn': 'Kodono',
    'lk': 'Lakè',
    'mtr': 'Mitro',
    'ntk': 'Monnotokpa',
    'shdd': 'Sèho Djigb',
    'sdj': 'Sodji',
    'ths': 'Togbohounso',
    'tkd': 'Tokpa-Koudjote',
    'tov': 'Tovè',
    'wzm': 'Wozounme',
    'ykn': 'Yokon',
    'zng': 'Zounguè',
    'zsl': 'Zounguè Saï Lagare',
    'znt': 'Zount',
  },
  'smk': {
    'all': 'Agbalilamè',
    'agd': 'Agblangandan',
    'agg': 'Agongo',
    'ags': 'Agonsa Gbo',
    'ahl': 'Ahlomè',
    'ahy': 'Aholouyèmè',
    'akk': 'Akpokpota',
    'ayk': 'Ayokpo',
    'dvt': 'Davatin',
    'dja': 'Dja',
    'dfg': 'Djèffa Glégbonou',
    'dfh': 'Djèffa Houédomè',
    'dhg': 'Djèffa Houédomè  Gbago',
    'dkn': 'Djèffa Kowenou',
    'djh': 'Djèho',
    'egm': 'Ekpè Gbédjamè',
    'ekn': 'Ekpè Kanhonnou',
    'ewd': 'Ekpè  Wéchindahomè',
    'ekk': 'Ekpè-Kpécom',
    'ekm': 'Ekpè-Marina',
    'ekp': 'Ekpè-PK10',
    'eks': 'Ekpè-Seyiv',
    'gkd': 'Gbakpodji',
    'ggb': 'Glogbo',
    'ggp': 'Glogbo Plage',
    'gh': 'Goho',
    'gdk': 'Hovidokpo',
    'kdc': 'Kadjacomè',
    'ktn': 'Kétonou',
    'ktt': 'Kétonou Tchinsa',
    'kkk': 'Kpakpakanmè',
    'kgd': 'Kpoguidi',
    'kkd': 'Kraké-Daho',
    'lkk': 'Lokokoukoumè',
    'mdk': 'Moudokomè',
    'oks': 'Okoun-Sèmè',
    'pdg': 'Podji-Agué',
    'pag': 'Podji-Agué Gbago',
    'pms': 'Podji-Missérété',
    'skj': 'Sèkandji',
    'sda': 'Sèkandji Allamandossi',
    'skh': 'Sèkandji Houéyogbé',
    'smv': 'Sèmè-Podj',
    'tcn': 'Tchonv',
    'tva': 'Tchonvi Agbologou',
    'thu': 'Tohouè',
    'tra': 'Torri-Agons',
    'wga': 'Wégbégo-Adiem',
  }
};
